### ISSUE TITLE
No eject? 

### ISSUE THREAD

**Issue by Vweber73** [vAmigaWeb/vAmigaWeb#110]
It seems that it is not possible to eject an adf or hdf other than by restarting the app, unless I'm missing something?

**Comment by mithrendal** [comment]
I tried your classic wb link and yes

![image](https://user-images.githubusercontent.com/17108995/182481001-c3a1b44a-a825-43f0-954c-5354de263d72.png)


it says "please remove workbench disk and reboot"

but I can not eject ... I did not have implemented a button for it ...

so I ended up exporting the hdf0 in the take snapshot dialog and restarted the app and loaded the exported hdf0 

here is the picture

![image](https://user-images.githubusercontent.com/17108995/182481506-f7427411-f99d-4230-a87c-14dec854c7d9.png)



we should have a way to eject...

**Comment by mithrendal** [comment]
![image](https://user-images.githubusercontent.com/17108995/182492141-97634763-3f2f-46a1-9f7a-9e72feba4524.png)

for the time being I did put the eject buttons into the settings dialog

pushed to uat

**Comment by mithrendal** [comment]
pushed another one ... beautified it a bit 😎

![image](https://user-images.githubusercontent.com/17108995/182523333-a2efc519-fb41-4f07-9e3c-adff9c63abad.png)

**Comment by Vweber73** [comment]
Excellent, thanks! But it will not work after introducing multiple drives (needed for a lot of games!).
Talking of beautification, the keyboard might need some :) at least the cursor and the numeric keypad keys should be aligned... ;)

**Comment by mithrendal** [comment]
>at least the cursor and the numeric keypad keys should be aligned... ;)

true. 🤓 we need to get more beautiful than this retroarch thing 🤩

do you think we could publish the current uat as an interims version to the public? It has the bugfix for this severe and critical  floppy insertion not detected bug…

**Comment by Vweber73** [comment]
Yes, the separate dialog will be fine, and yes, this version looks quite stable!
Cheers

**Comment by mithrendal** [comment]
A volume setting for floppies and harddisks 🙃

**Comment by mithrendal** [comment]
Do you have a motor sound?

**Comment by Vweber73** [comment]
I don't! But maybe winuae has a free one? :)

**Comment by mithrendal** [comment]
fixed in v2.1b5 pushed to regular version
