### ISSUE TITLE
borderless draws checker board on reset

### ISSUE THREAD

**Issue by mithrendal** [vAmigaWeb/vAmigaWeb#115]
@vWeber73 noticed it...

my findings: on reset the core sends me as viewport trackuing coordinates 0 0 0 0. I don't know yet what this should mean... but when I ignore the 0 0 0 0 message then everything seems fine

**Comment by mithrendal** [comment]
@Vweber73 pushed to uat

**Comment by Vweber73** [comment]
Thanks, I confirm it is solved, even though it was not critical! :)
