### ISSUE TITLE
No Sound iPadOS16.1 (Latest Build)

### ISSUE THREAD

**Issue by aZtOcKdOg** [vAmigaWeb/vAmigaWeb#131]
I can't seem to get any sound after using the latest build (core 2.2b1 / ui 2022_11_12)

Am I missing a setting or is this an issue?

**Comment by mithrendal** [comment]
Hi @aZtOcKdOg  ... could be ... but most likely iPad is muted see https://github.com/vc64web/virtualc64web/issues/167

on iPadOS it is hard to see whether being muted or not ...

could you try to de-mute it ?

**Comment by aZtOcKdOg** [comment]
G'day @mithrendal, thanks for the suggestion it was another app taking control of audio I think... bizarre never had that issue before but I will have a look at my browser settings to make sure multithread audio is enabled or what state background audio in the particular app that I had running is set to!

Thanks now PT-1210 is working great again yay!
