### ISSUE TITLE
Can´t load the pwa 

### ISSUE THREAD

**Issue by beronk** [vAmigaWeb/vAmigaWeb#132]
Hi, first congratz for this amazing pwa, i have an iphone 12 and started to have problem in the moment i tried to update the pwa for the new version, when i tried to open the pwa its freezes in the booting into vAmiga WebEdition... can you help me? Even on safari it doesn´t work, tried deleting but the issue still persist.
thanks.

**Comment by mithrendal** [comment]
@beronk ok lets troubleshoot… please try to answer the following questions 

1. Is the black screen showing up? 
2. does it work when you use a private browsing tab? 
3. can you still go into vAmigaWeb settings?

**Comment by beronk** [comment]
1.The black screen is showing up in the loading loop "booting into vAmiga..... preparing". 
2. No stays the same in the loading loop.
3. yes i can go into the settings but can´t play do nothing on it
4. ios 14.6 and worked fine 
I was so happy i could finally play Amiga500 on my iphone and for me one of the best emulators and simple a very easy to use  the games work flawless :)

**Comment by beronk** [comment]
Ops sorry didn´t read the  notes i updated the iphone and works like a charm:).
Thank you for this amazing emulator :)

**Comment by mithrendal** [comment]
>I was so happy i could finally play Amiga500 on my iphone and for me one of the best emulators and simple a very easy to use the games work flawless :)

we are glad that it works now for you and that you are enjoying our project ... and also thank you for your kind words ❤️...
