### ISSUE TITLE
Support extended ADF files

### ISSUE THREAD

**Issue by mras0** [vAmigaWeb/vAmigaWeb#141]
Supporting extended ADF files (already supported in vAmiga via the `EXTFile` class) might be necessary for Hoi (https://github.com/dirkwhoffmann/vAmiga/issues/762). It looks like it's not currently possible to mount these files in vAmigaWeb.

On the code front I think it should be enough to add another if block to `load_disk` in `mainsdl.cpp` (Note: `EXTFile::isCompatible(string)` always returns true, so probably easiest to just place it last), but maybe the GUI also needs to be updated.

Tried to add it myself, but I can't get a locally built version to work.

**Comment by mithrendal** [comment]
added like you said on my machine

```

#include "EXTFile.h"

...

  if (EXTFile::isCompatible(filename)) {
      printf("%s - Loading EXT file\n", filename);
      EXTFile ext{blob, len};
      return std::make_unique<FloppyDisk>(ext);
    }

```

and the compile succeeds...

so when the extension is also ADF then it should be enough like this right ?

**Comment by mithrendal** [comment]
pushed it to test environment 😎
https://vamigaweb.github.io/uat/

**Comment by mras0** [comment]
I think it's filtered in the GUI, maybe here: https://github.com/vAmigaWeb/vAmigaWeb/blob/96b86872350f5a8860064aca285d43e88809e048/js/vAmiga_ui.js#L914

Here's a small one that should work: [show_regs.zip](https://github.com/vAmigaWeb/vAmigaWeb/files/10251426/show_regs.zip)

I don't know if there's a standard extension for these files. If people also just call them ".adf" maybe it's better not to change the GUI and instead load like this:
```
    if (ADFFile::isCompatible(filename)) {
      printf("%s - Loading ADF file\n", filename);
      try {
        ADFFile adf{blob, len};
        return std::make_unique<FloppyDisk>(adf);
      } catch (const VAError& e) {
        // Maybe it's an extended ADF?
        printf("Error loading %s - %s. Trying to load as extended ADF\n", filename, e.what());
        EXTFile ext{blob, len};
        return std::make_unique<FloppyDisk>(ext);
      }
    }
```

**Comment by mithrendal** [comment]
I see your point. Will check what winuae accepts for extensions … we can lean on their behavior

**Comment by mithrendal** [comment]
winuae file dialog 

<img width="306" alt="image" src="https://user-images.githubusercontent.com/17108995/208243186-9dbd0074-4f47-4211-93be-e3ec82e0d612.png">

hmm no .ext file extension  ... can not insert the showreg.ext file with this dialog

lets try drag and drop ...

yes that works ... hmmm what should we do now ?

**Comment by mras0** [comment]
People probably expect extended ADFs to work with a ".adf" extension then (Example: https://github.com/dirkwhoffmann/vAmiga/issues/672), so probably what I suggested above (first try to load as a normal ADF, and if that fails, load as an extended one).

**Comment by mithrendal** [comment]
🙋🏻ok did as you instructed me ... and published to test environment

https://vamigaweb.github.io/uat/

EDIT: for me loading show_regs works now 😍... 

maybe @rhinoid s game works now too with sound ?

then we can publish to the regular version now?

**Comment by mras0** [comment]
Yes, seems to work 👍 Hoi intro music is now playing for me with the extended ADF version of the disks.
