### ISSUE TITLE
Audio problem

### ISSUE THREAD

**Issue by PTz0uAH** [vAmigaWeb/vAmigaWeb#150]
Hoi there.. amazing project! I experience audio problems.. I run the vAmigaWeb.github.io hosted locally, adapted the url in vAmigaWeb_player.js and everything works fine.. except the game audio is not active.. the floppy sounds on the other hand are played.. using latest firefox on windows..

**Comment by PTz0uAH** [comment]
@mithrendal
I guess vAmigaWeb is not to blame.. it has something to do with my local httpserver since the emulation at vAmigaWeb.github.io is running fine with audio (using AmigaTestKit.adf and kick3.0).. looks like I have to include some missing wasm mimetype in the http server I'm using.. (Tiny webserver came with fullsource so I'll try to make it work because I don't want to use https locally)..
![vAmigaWeb_audio_error_001](https://user-images.githubusercontent.com/87427309/216113300-65700319-5b78-4bf1-aba4-86b69157ab00.jpg)

**Comment by mithrendal** [comment]
<img width="434" alt="image" src="https://user-images.githubusercontent.com/17108995/216132293-773d215a-19b1-450f-8c38-b6302d50195e.png">

do you see these lines ? maybe it does not connect the main thread to the audio processor thread...

**Comment by PTz0uAH** [comment]
the lines you mention only come up if Firefox visits vAmigaWeb on localhost(http) or the one hosted at vAmigaWeb.github.io(https) and signals the gameaudio works ok.. but if connect to this httpserver from another pc in the LAN the audio is not working (floppydrive-sounds are audible, emulation runs fine).. hmm I could try running a httpserver on the linuxmachine in the LAN to see if it makes a difference.. 
![vAmigaWeb_audio_error_002](https://user-images.githubusercontent.com/87427309/216439448-930536ca-f2d9-4aab-919b-4b8dba8b57ab.jpg)

**Comment by mithrendal** [comment]
I tested here an can confirm that chrome does not play the paulas Amiga sound when run from solely from unsecure http... 

you have two options here 
1. upgrade the webserver to https
or
2. tell the browser to treat the unsecure connection as secure for example using chrome with [chrome:/flags](chrome://flags/)  (--unsafely-treat-insecure-origin-as-secure)

**Comment by PTz0uAH** [comment]
Thanks for the hints, I installed vAmigaWeb on a https server which indeed made the paula-audio audible again.. so I ran some programs after AmigaTestKit was OK.. played the Default.perf track in Music-X2.0 which runs fine.. (8svx tracks sound ok, cannot test the midi ).. & also found 2 possible bugs in the (audio) system.. 1) when switching to another tab in Firefox the emulation should be muted yet some annoying crackling leaks through.. yet disappears after switching back to the vAmigaWeb tab..  2) with an extended test booting vAmigaWeb from HDF WB3.1 + running the memory-hungry AmiBlitz3 (takes 8mb).. I successfully compiled a protracker modplayer which plays a mod + triggers a "clap"sample.. after the "clap" sounds constant ringing hi-freq "static" is introduced.. which only disappears after "reset"..

**Comment by mithrendal** [comment]
regarding 1) 

a.) I reproduced it only on firefox but effect maybe on other platforms too
b.)  this line of code pauses the emulation on tab suspension and therefore also the audio pipeline mutes
  `window.addEventListener("blur", async ()=>{await action("pause")}); `

 but I guess this side effect is not quite what we want right?...because when reentering it is still paused... it should better remember its state before suspension and on reentering the tab it has to  rerun if its state was running before suspending the tab

should be handeled in a new issue would you open one?

regarding 2)
have you peeked into the javascipt console for errors when this happens ? Maybe some memory constraints got out of bounds here ... or something like that?

**Comment by PTz0uAH** [comment]
Although the audio runs fine by vAmigaWeb hosted on external https server.. I'm still looking for an easy way to run vAmigaWeb on the LAN, so the audio-problem is partly solved.. If the external site is down there would be no fallback option including paula-audio so I have to test some simple server options which might work ( simple-https-server.py or even a ESP32 hosting https-site from sd-card ) that will take some time to figure it out.. & will report the findings overhere..

In the meantime I've monitored the Audio-Bug2 candidate and could not find any JS debug messages concerning faulty/overdriven audio so I think the emulated paula is clipping and triggers a feedback loop of some kind inside the vAmiga core..

While booting up with my favorite game (ChaosEngine) I found also an Audio-Bug3-candidate concerning missing 1 or more paula-audio-channels.. after the game, with bootsector audio/gfx intro loads, there is a possible problem with re-initializing the paula-audio which sounds like missing audiochannel-context during the rest of the game..

**Comment by PTz0uAH** [comment]
Hoi @mithrendal since I expanded my devscope from FireFox-only to a custom Chromium.. I found that option (chrome equivalent) to run vAmigaWeb from a local HTTP server including Amiga game-audio..

So what you suggested earlier fpr Chrome works also fine for Chromium albeit called differently..

> 
tell the browser to treat the unsecure connection as secure for example using chrome with chrome:/flags (--unsafely-treat-insecure-origin-as-secure)

Too bad I couldn't find a FireFox equivalent but did found that was reported as bug at mozilla..

I guess for me the audio problem is resolved since I now use the cef4delphi framework to get things done with chromium..
