### ISSUE TITLE
Minimizing or Firefox tab change causes unexpected audio-behaviour

### ISSUE THREAD

**Issue by PTz0uAH** [vAmigaWeb/vAmigaWeb#151]
Bug: If the browser is minimized or after tabchange the vAmigaWeb page, some annoying audio-artefacts are "leaking" through..

Expected behaviour: the emulation pauses, the audio mutes and the emulation continues with unmuted audio after switching back to the vAmigaWeb tab..

..other browsers could also be affected..

**Comment by PTz0uAH** [comment]
Comment: I 've noticed that the bug does NOT appear if vAmigaWeb is running inside JS windows.. covering up the vAmigaWeb window with another JS window does not interfere with the audio/emulation which keeps running.. furthermore if the JS window is minimized the behaviour seems correct.. the emulation pauses & no audio artefacts leakage & when resumed it just continues.. like it should.. so this is how I'm gonna implement vAmigaWeb..
![No_Audio_Bug_In_JS_Windows](https://user-images.githubusercontent.com/87427309/222887543-9e918793-1c6a-4f87-8ca3-cca2b12d3be8.jpg)

**Comment by mithrendal** [comment]
Hi @PTz0uAH I have fixed it on branch `nosdl2` which is going to be the next version … 

The fix listens whenever the visibility changes  between either `visible` or `hidden`. On hidden it mutes the soundprocessor i.e. when Amiga canvas is not visible either tab or minimised.

Here is the code fragment…
```javascript

//when app becomes hidden/visible
 window.addEventListener("visibilitychange", async () => {
     if(document.visibilityState == "hidden") {
        try { audioContext.suspend(); } catch(e){ console.error(e);}
     }
     else
     {
         try { await connect_audio_processor(); } catch(e){ console.error(e);}
     }
 });
```

**Comment by PTz0uAH** [comment]
Hoi @mithrendal.. nice work to tackle that bug..

Considering that screenshot.. it's the real deal from our own site.. I was allowed by the friendly author of TAWS (The Amiga Workbench Simulation), Michael Rupp to use TAWS for our (my son and I) fun-site..  he shared the full source and I updated it for PHP8+ usage and with the vAmigaWeb implementation as proofofconceptofproof it became very..very.. realistic.. Basically I just did what I wanted to do 10+ years ago (run an Amiga emu inside webpage via NPAPI) and thanks to at first..SAE and now vAmigaWeb it became reality.. The TAWS author is working now on a version 36 .. take a look at his site taws.ch it's a great experience for amiga lovers..

Anyway.. keep up the good work & here another "teaser" aka wishlist..
![TAWS4AmiGoXPE_ShowCase2](https://user-images.githubusercontent.com/87427309/222906963-587f3cb4-f197-4428-b84c-db2981e63210.jpg)

**Comment by mithrendal** [comment]
pushed the new version out to the regular https://vamigaweb.github.io address... which includes the fix for this issue among many other things... I close the issue then...

concerning your wish list

+ `ser:` should be possible to route that into a javascript call where you can do what you want with incoming data... needs some investigation... I did something like that once for vc64web

+when you did coding inside vAmigaWeb and want to` export the hdf or adf` then just click the snapshot icon in the navbar there you can export the current states of the disks

+MIDI oh I don't know how to do that ? probably via the `ser:` ?

**Comment by PTz0uAH** [comment]
@mithrendal  thanks again for your efforts.. 

I obviously missed that already available snapshot option..

even if you could get simple tx/rx access to the default vAmigaWeb serial port to work that would be mega cool.. (lowlevel debugging/romwack/sernet)

and you are right concerning midi for amiga.. amiga midi (31250BAUD) uses the same serial device (via a midi.library) as the **Amigados console NewShell aux:** does.. just slightly differently configured..

on the real A1200 I configured the WB serial device at MIDI speed instead of the default 9600BAUD and that works like a charm even through the homebuild midi/serial-interface..

so if the serial port (paula-uart) would be activated for vAmigaWeb one could for example relay a duplex serial midi stream to/from the widely supported WEB-MIDI-API if running octamed/musicx/barsnpipes/scala/etc-midi-progs/games & if workbench or another program (multiplayergame/sasc/blitz2/amos/arexx/etc.) requires simple serial.device access.. that duplex stream could be proxied via JS interface or even perhaps via a tcp socket server like fs-uae/winuae does..

I hope there would be enough "virtual cpu overhead" to get that working without compromising the cycle-exactness.. it would introduce a plethora of usage possibilities from back in the day.. 

Well, I'm gonna do some serialport studying from my side.. might bring some usefull insights..

**Comment by mithrendal** [comment]
Regarding the serial port I spoke with @dirkwhoffmann and it should be possible without patching the vAmigaCore lib itself … so yes I will give this a try then in the coming days, weeks…😎… we should open a new issue for this then…
