### ISSUE TITLE
Serial port missing or not activated..

### ISSUE THREAD

**Issue by PTz0uAH** [vAmigaWeb/vAmigaWeb#154]
Hoi @mithrendal

If vAmigaWeb runs serialport enabled Amiga-programs "nothing" happens yet no "error" comes up..

Though the vAmigaCore2.3 has a built-in feature to handle paula-uart communication it is not yet implemented in vAmigaWeb..

I sincerely hope you can get it to work..

To be able to use the AUX: terminal connection or SER:  communication (& MIDI) would be a great addition imho..
![No_SerialPort_or_MIDI_Enabled](https://user-images.githubusercontent.com/87427309/224188603-711e16d5-b0b1-40d2-8cc3-f9854d44294d.jpg)

**Comment by mithrendal** [comment]
Lets do it… 😎. First step will be to be able to summon the RetroShell in order to debug the serial port …

**Comment by mithrendal** [comment]
@PTz0uAH  serial port for **outgoing** data has been implemented ... is it this what you need ?

### vAmigaWeb lives in the same window instance ... 

then you can set your own serial port handler like so

```javascript
let my_own_receive_buffer="";
set_serial_port_out_handler((raw_data) => {
 //transform the raw data to a string
 let char = String.fromCharCode( raw_data & 0xff );
 //do what you want with that character
 my_own_receive_buffer += char;
});
```

the default implementation does the following...

```javascript
set_serial_port_out_handler((data) => {
    //clear buffer when nobody consumes after 4kb of incoming data
    if(window.serial_port_out_buffer.length>4096)
    {
        window.serial_port_out_buffer="";
    }
    window.serial_port_out_buffer += String.fromCharCode( data & 0xff );
    //if we are embedded in a player send serial data to the host page
    window.parent.postMessage({ msg: 'serial_port_out', value: data},"*");
});
```

### your vAmiga lives in a player instance that is in an iFrame 

in this case you can not directly access vAmigaWeb API you have to use a message queue instead

```javascript
//the following lines of code demonstrate how to receive serial data from a vAmigaPlayer instance 
let out_buffer="";
window.addEventListener('message', event => {
    if(event.data.msg == 'serial_port_out')
    {
        let byte_from_amiga=event.data.value;
        out_buffer+=String.fromCharCode( byte_from_amiga & 0xff );

        if(out_buffer.length>80)
        {
            console.log(out_buffer);
            out_buffer="";
        }
    }
});
```

**Comment by PTz0uAH** [comment]
Hoi @mithrendal.. Your magic really works with a basic test.. Looks promising..
![vAmigaWeb_SerialPort_Test_01](https://user-images.githubusercontent.com/87427309/226499890-63271ff7-3d8f-4401-96a6-c34a7374094b.png)

**Comment by PTz0uAH** [comment]
@mithrendal This is great.. behold the Amiga boot prompt..

vAmigaWeb [NewShell AUX:] (OUTPUT) is fully functional with my AmiGoDOS Developer Shell..

Next step would be if possible [NewShell AUX:] (INPUT) to be activated so we can actually use vAmigaWeb in the "OldSchool" way just like a real Amiga..

Here the evidence of that "close encounter"..
![PR00F_0F_C0NCEPT 2023-03-22 at 18-24-26_SERIAL_AUX_OUT](https://user-images.githubusercontent.com/87427309/226993951-0edfc0a0-1c99-4790-b244-020943ea110a.png)

**Comment by mithrendal** [comment]
Very cool stuff indeed… 😎

To get the input direction working I have to wire the javascript null modem cable onto the correct pins of the CIA … I did the same for the https://vc64web.github.io  

For reference https://github.com/vc64web/virtualc64web/wiki/serial_cable

@dirkwhoffmann are the pins to which we have to solder the virtual cable the same in the C64 and the Amiga ?

**Comment by dirkwhoffmann** [comment]
> @dirkwhoffmann are the pins to which we have to solder the virtual cable the same in the C64 and the Amiga ?

Unlike the C64, the Amiga does not utilize the CIAs for serial communication. The serial port is driven by a separate UART which is part of Paula. The best starting point is to look at the implementation of the serial cable (which can be used to connect two vAmiga instances via socket connections):

https://github.com/dirkwhoffmann/vAmiga/blob/master/Emulator/Misc/RemoteServers/SerServer.h
https://github.com/dirkwhoffmann/vAmiga/blob/master/Emulator/Misc/RemoteServers/SerServer.cpp

Your implementation will have to do what the external vAmiga instance does on the other side of the socket connection.

**Comment by mithrendal** [comment]
@dirkwhoffmann that helps a lot … it seems the cable is already built-in 😍… we only have to hand over the text into the UART via your `remoteManager.serServer` … 

I tried this …

```c
bool is_connected=false;
extern "C" void wasm_write_string_to_ser(char* chars_to_send)
{
    if(!is_connected)
    {
      wrapper->amiga->remoteManager.serServer.didConnect();
      is_connected=true;
    }
    wrapper->amiga->remoteManager.serServer.doProcess(chars_to_send);
}
```

and thats maybe already enough to feed the signals into the UART thing


Lets try `type ser:`

And these javascript lines put into an `ActionButton`

```javascript
let some_text =`this text has been sent from javascript... 
it has been sent into the Amiga via its serial port which is 
now connected to the outer world...`;
wasm_write_string_to_ser(some_text);
```

@PTz0uAH first contact … 🤤

![3ED2B1F0-411A-48BA-B21A-BB3F6CB1166B](https://user-images.githubusercontent.com/17108995/227657024-b0e015f7-d2b9-4e9c-ad09-e7d4f0a161a8.jpeg)

When I click the action button several times it keeps writing into the CLI window. I gave the action button the shortcut key `t` … then I can flood the Amiga with text 😎 by hitting frequently the `t` key.

**Comment by dirkwhoffmann** [comment]
Great to see that it works so well!

Since the serial port is used actively now, I've taken some time to enhance the documentation. I've added an article describing how two vAmiga instances can be connected via a null model cable:

https://dirkwhoffmann.github.io/vAmiga/docs/HowTo/NullModemCable.html

**Comment by PTz0uAH** [comment]
Gentlemen.. the magic is real.. behold the sound of silence to celebrate this achievement..
While no midi api connected yet I hope you like this aubade..
![Screenshot 2023-03-25 at 13-37-30 tsoca amigoxpe net](https://user-images.githubusercontent.com/87427309/227718381-2f50a9dd-fc22-4043-a29b-d8aa83b7a995.png)

**Comment by PTz0uAH** [comment]
@mithrendal I can also confirm the hwSerial loopback works from a button

Amigados however is not aware of the string entered, the string is just echoed via [AUX:](OUTPUT)..
![buttontest](https://user-images.githubusercontent.com/87427309/227781093-0edd3edf-e667-4451-875c-64a1aad3596a.png)

**Comment by mithrendal** [comment]
What exactly is AmiGoDOS and what does it do ? Is the source code of AmiGoDOS anywhere so that we can take a look into it ? Which commands do you execute on the AmigaDOS side … and how you want to connect MIDI ? 

In @dirkwhoffmann serServer is a pre-buffering of 8 bytes implemented… i.e. if one feeds less then 9 bytes it will wait with feeding them into Paula’s UART … as far as I understood the code … 

Look here 

```
void
SerServer::serviceSerEvent()
{
    assert(agnus.id[SLOT_SER] == SER_RECEIVE);
    
    if (buffer.isEmpty()) {
        
        // Enter buffering mode if we run dry
        buffering = true;

    } else if (buffering) {
        
        // Exit buffering mode if now new symbols came in for quite a while
        if (++skippedTransmissions > 8) buffering = false;

    } else {

        // Hand the oldest buffer element over to the UART
        uart.receiveShiftReg = buffer.read();
        uart.copyFromReceiveShiftRegister();
        processedBytes++;
        skippedTransmissions = 0;
    }
    
    scheduleNextEvent();
}
```


Also on my tests with `type ser:` I discovered that I had to feed a lot more then these 8 bytes into the Amiga to make them appear on the CLI window…  maybe there might be also some sort of buffering in AmigaDOS ?

Is there any AmigaDOS programm which can monitor the serial port in realtime ?

**Comment by mithrendal** [comment]
Okay I did some tests… on `type ser:`

When I write 200 bytes then `type ser:` shows nothing …

When I write the next 200 bytes (not even one byte less) … then `type ser:` shows the first 200 bytes

And so on….

![BC6527F4-C162-44CE-A7E4-060815505C18](https://user-images.githubusercontent.com/17108995/227792672-b088bf03-fc75-404f-a4dd-a9b87abe696a.png)

  
Can someone explain to me why `type ser:` flushes every 200 received bytes and not immediately what it receives into the CLI window?

**Comment by mithrendal** [comment]
found a bug ... after an emulator reset the
 
```javascript
wasm_write_string_to_ser(some_text);
```

wasn't working anymore ... just published a bugfix for this. 

Now whenever one calls that function it checks whether agnus does already services `SERIAL IN events` and in case if not ... it registers for these events.

**Comment by PTz0uAH** [comment]
@mithrendal some info & progress

1) I have put some info/code about AmiGoDOS in my forked repository of vAmigaWeb..

2) For midi we can connect to the WebMidiApi or perhaps via a websocket I will investigate that later after the basic AUX stuff works..

3) Also created a little serial test program with BlitzBasic and now I can confirm the buttons are working.. YEAH!
![SerialPortBlitzBasic](https://user-images.githubusercontent.com/87427309/227849673-a5984f0b-2421-4a15-b8e5-1121b24d4085.png)

**Comment by mithrendal** [comment]
Ah ok now I see what you are doing … looks great😎.  

I also see what you need next… i.e. you can not use `wasm_write_string_to_ser(some_text);` directly because your terminal code is not living in the same frame as the emulator … currently you are using `ActionButtons` for testing purposes which live in the same emulator frame (i.e. not in the main window) so this works. 

solution is to use `postMessage` method to communicate with the vAmigaWeb instance which lives in the vAmigaWeb player iframe window…

For this you would post a message to the emulator window when you type `showconfig` in your AmiGoDos terminal (which itself is living in the html host window). 

```javascript
//get the vAmigaWeb iFrame window
let vAmigaWeb_window = document.getElementById("vAmigaWeb").contentWindow;

//send a message to the serial port of vAmigaWeb e.g. showconfig
vAmigaWeb_window.postMessage("ser:showconfig", "*");
```

I will add the `ser:` listener code on the vAmigaWeb side in the next couple of days … where I receive the message and translate it then in a `wasm_write_string_to_ser()`call.

Does it sound ok for you ?

**Comment by mithrendal** [comment]
>SOLVED!: well I managed to get it done via a button so I guess it will also work when the ser: listener is implemented..

very cool !

also news here ... I am just implemented the `ser:` command via postMessage with which you can post data from outside into the serial port of the Amiga living a vAmigaWeb_player. I slightly changed the above proposed syntax...

```javascript
function send_hello_to_ser(){
    //get the vAmigaWeb iFrame window
    let vAmigaWeb_window=document.getElementById("vAmigaWeb").contentWindow;

    //data that should be written into the serial port
    let data="hello";

    //send the data to the serial port of vAmigaWeb
    vAmigaWeb_window.postMessage({cmd:"ser:", text: data}, "*");
}
```

**Comment by PTz0uAH** [comment]
@mithrendal thats great.. got it implemented with AmiGoDOS.. so I'm gonna put IT to the test and I'll post the results..

**Comment by mithrendal** [comment]
Currently we setup an API that relies on strings … we could also implement a binary feed …do we need that ?

E.g.

```javascript

let _BREAK_ = 0x03;

//lets send two times a CTRL-C
let some_uint8_array = new Uint8Array(2);
some_uint8_array[0]=  _BREAK_;
some_uint8_array[1]=  _BREAK_;

//direct feed via actionbutton
wasm_write_bytes_to_ser(some_uint8_array);

//feed binary data into a vAmigaWeb_player 
vAmigaWeb_window.postMessage({cmd:"ser:", bytes: data}, "*");
```

**Comment by PTz0uAH** [comment]
@mithrendal the implementation for AUX is working fine.. absolutely wonderful.. no more buttons needed.. 

Although binary feed might come in handy when we investigate the MIDI or even the raw ser comm.. we could use the `String.fromCharCode` for it is a versatile function.. we'll see..

Hope you like it so far..

![TS0CA_Old-School_AUX_OK](https://user-images.githubusercontent.com/87427309/229353001-7337206a-8959-456d-8575-3522c5991ed3.png)

**Comment by mithrendal** [comment]
I like it !!! Really whish 🤤 to type myself to your AmiGoDos Shell … is there any plan to bring this cool thing to the public so people can see and try it ? It needs a php backend right ? Maybe on this TAWS website you mentioned earlier ? 


> is vAmigaWeb able to start a snapshot via URL/JSON arguments?..

just save/export the snapshot as a `.vAmiga` file and reference it in the `url` parameter of the player should do …

**Comment by PTz0uAH** [comment]
> just save/export the snapshot as a .vAmiga file and reference it in the url parameter
Well I've done that before and it worked yet when using multiple large HDFs (128MB)  on my external server there are performance issues and that's what I meant.. Refrased.. `Is it possible to directly boot from local storage via URL/JASON parameters or switch?`.. that is much more logical/faster imho..  or perhaps an additional switch to autoboot from the last saved working-environment (or by name).. That way it is a kind of a "productivity booster".. since AmiGoDOS also saves all history-commands to local storage.. so they are always available..

Of course I am "cooking" a couple of "The Spirit of.." (TS0CA) showcase-sites.. 1 for dev with on-the-edge/ the latest changes.. and 1 for guests without the need for login.. and some multiple "experimental playgrounds".. I updated TAWS for PHP8.1+ usage so any vAmigaWeb-php should follow that minimal version for compatibility..

**Comment by mithrendal** [comment]
serial port support is completed ...

we have can now send text, one byte or a byte buffer

```javascript
wasm_write_string_to_ser(“hello can you hear me ?”);
   
wasm_write_byte_to_ser(0x03); //CTRL-C

wasm_write_bytes_to_ser(uint8_byte_array_buffer);
```

```javascript
    let text_data="sending text";
    //send the data to the serial port of vAmigaWeb
    vAmigaWeb_window.postMessage({cmd:"ser:", text: text_data}, "*");

    //single bytes
    let byte_buffer=(new TextEncoder()).encode(" sending single bytes");
    for(let b of byte_buffer)
        vAmigaWeb_window.postMessage({cmd:"ser:", byte: b}, "*");

    //bytebuffer
    let complete_buffer=(new TextEncoder()).encode(" sending a byte array");
    vAmigaWeb_window.postMessage({cmd:"ser:", bytes: complete_buffer}, "*");

```



the following wiki page describes all methods  ...
https://github.com/vAmigaWeb/vAmigaWeb/wiki/serial_port

@PTz0uAH for your question regarding the start of a snapshot from local storage we open a new issue

**Comment by PTz0uAH** [comment]
PTz(💯% OK & Thanks!)uAH
