### ISSUE TITLE
javascript console is flooded with debug output

### ISSUE THREAD

**Issue by mithrendal** [vAmigaWeb/vAmigaWeb#16]
@chris70c has reported this... we should disable it as a default measurement and  implement a setting to be able to enable debug output in case it is needed

**Comment by mithrendal** [comment]
this article is about the performance impact of javascript console logging which is used extensively by vAmigaWeb

https://stackoverflow.com/questions/11426185/will-console-log-reduce-javascript-execution-performance

it reads scaring 😱... @chris70c was so right about it ... what a drama if true ... but see yourself


---------------
- when the browser console is closed, calling console.log is about 10 000 times slower than calling an empty function

- when the console is open, calling it is as much as 100 000 times slower._
---------------

maybe its time to disable logging completely (i.e. no logoutput at all in the javascript console)... 

when logging console is not loaded

![image](https://user-images.githubusercontent.com/17108995/185477779-e24c7d20-64e0-4c81-8d1b-adfd86db5501.png)

and we can enable logging to console when the switch is enabled....

![image](https://user-images.githubusercontent.com/17108995/185478169-9421fbc0-298b-4fab-aabb-c9da3b17fb77.png)

@Vweber73  this could also reduce or eliminate timing issues when our devices are under pressure i.e. when overclocking an 68030 to 28Mhz

**Comment by Vweber73** [comment]
Great finding!
So i understand that the "show console" switch,  when set to off,  only stopped showing the console,  but not the logging itself? Maybe the behaviour of this switch should just be altered so that nothing is logged at all when set to off?

**Comment by mithrendal** [comment]
>So i understand that the "show console" switch, when set to off, only stopped showing the console, but not the logging itself?

correct thats how it currently works, and that is where the article says 10000 slower than empty function ... 

I just cannot understand why it is that expensive ? That is a crazy high multiplier ... unbelievable



>Maybe the behaviour of this switch should just be altered so that nothing is logged at all when set to off?

yes. I saw for example while disk loading activity we log all the motor step events ... we don't need it when  playing a game right ? Only when we want to look at it for debugging purposes then we enable it in the settings...

**Comment by Vweber73** [comment]
Well then let's not log anything unless the switch is on!

**Comment by mithrendal** [comment]
pushed to uat

flooding stops when switch is off... although I left some logs in the code, now the log will not constantly grow now when switch is off  

to be honest I saw not so much of a massive improvement on my old macbook pro from 2007

therefore I did for testing reverted also TPP=2 back to TPP=1, which makes the ECS super hires mode a bit blurry...  but for games this mode is quite useless and with TPP=1 the emulator only has to generate half of the pixels compared to TPP=2

**Comment by Vweber73** [comment]
Thanks! 

I tried this one with Settlers.

The TPP2 effect might be greater than the logging effect... When still logging,  now I have no frame drop until 43Mhz included (but I still have glitches here and there). The drops starts at 57Mhz. When I remove the logging,  basically from what I can ear,  the problem is shifted to the 85Mhz bar,  57Mhz still sounds reasonably ok... 

This TPP2 thing is ennoying,  especially because it seems there is no way to trigger it only in super hires mode,  it is either you have it or you don't,  right? 

Cheers

**Comment by dirkwhoffmann** [comment]
> it is either you have it or you don't, right?

Yes, it's a compile time option. Otherwise, it would take too much computation time (the code had to be flooded with lots of `if (TPP == xxx) { do this } else { do that }`.

**Comment by Vweber73** [comment]
Hum,  go it,  thanks. Maybe 2 versions then,  one "serious ECS work" one and one "pure gaming" one,  with a hotswapping between the 2?

**Comment by Vweber73** [comment]
Interesting finding in favour of the performance of vAmigaWeb compared to Retroarch / Puae.

When using 68030 and selecting max map size (8), in Settlers,  the game enters a computation phase with a red progress bar.  VAmigaWeb does this right,  but Puae struggles,  the music is screwed up...

**Comment by mithrendal** [comment]
logging is now turned off if the `load logging console` switch is off
