### ISSUE TITLE
directly boot from local storage via URL/JSON parameters

### ISSUE THREAD

**Issue by mithrendal** [vAmigaWeb/vAmigaWeb#167]
this is a question by @PTz0uAH :

Is it possible to directly boot from local storage via URL/JSON parameters or switch?

**Comment by PTz0uAH** [comment]
@mithrendal that works great.. restoring a snapshot from AmiGoDOS in a couple of seconds.. whoosh..

I wonder if one could call those script actions also via vAmigaWeb.postMessage construction.. I tried various ways to call 'take_snapshot' from the shell yet could not get it to work..

Also I had to temporary disable 'grab_focus' for AmiGoDOS to keep the cursor.. until I find another way.. 

> //document.getElementById("vAmigaWeb").onload = this.grab_focus;

**Comment by mithrendal** [comment]
@PTz0uAH 

that is straight forward ... just use the players exec function for that

syntax: 
```javascript

vAmigaWeb_player.exec(function, param);

/* example*/
vAmigaWeb_player.exec((t)=>alert(t), 'hello');

/* example param can be undefined so this also works */
vAmigaWeb_player.exec(()=>alert('hello'));

/* or this */
vAmigaWeb_player.exec(()=>action('take_snapshot'))
```

some buttons? ... just do this on your hosting web page....

```javascript
<button type="button" onclick="vAmigaWeb_player.exec(()=>alert('hey'))">exec without param</button>
<br>
<button type="button" onclick="vAmigaWeb_player.exec((t)=>alert(t), 'hello')">exec with param</button>
<br>
<button type="button" onclick="vAmigaWeb_player.exec(()=>action('take_snapshot'))">exec take snapshot</button>
```

of course theoretically one could also do some serial communication this way .... since the function has to be serialized before sending it to the other window it adds more processing overhead compared to the regular way of feeding the serial port ... but I doubt anybody would notice the difference 

```javascript
vAmigaWeb_player.exec((text)=>wasm_write_string_to_ser(text), 'an alternative way of feeding the serial port');
```


can I close the issue ?

**Comment by PTz0uAH** [comment]
@mithrendal  sure close it up.. and thanks for explaining
