### ISSUE TITLE
vamigaweb.github.io no longer boots certain ROMs after 3-4 update

### ISSUE THREAD

**Issue by PTz0uAH** [vAmigaWeb/vAmigaWeb#168]
@mithrendal  I checked it a couple of times but the site won't boot 3.1 rom anymore..

the firefox debugger hangs until switching back to lower/higher rom..

I cleared the cache to make sure it is "buggy behaviour"

**Comment by mithrendal** [comment]
Please check whether the rom needs 68020 and also check currently selected CPU

**Comment by PTz0uAH** [comment]
@mithrendal that was it!

It would seem to be the case that after an update of the core the settings are lost..

So this is a non-issue.. Thanks again!
