### ISSUE TITLE
Dark Bottom Bar not activated on launch...

### ISSUE THREAD

**Issue by aZtOcKdOg** [vAmigaWeb/vAmigaWeb#177]
Now... this could just be an inherent issue with iPadOS itself but is present even when 'Dark Mode' is checked in vAmigaWeb GUI settings and Dark Mode is also active as my iPadOS default.

On first launch (incorrect):

![image](https://github.com/vAmigaWeb/vAmigaWeb/assets/64781882/f5a95a39-1226-460d-ac43-5dfe95fc408d)

After switching apps and back (correct):

![image](https://github.com/vAmigaWeb/vAmigaWeb/assets/64781882/cd7ab969-ac13-407c-a18a-abb1d48bfbe3)

I just thought there may be an initial check that isn't performed?

Not sure what checks or initiates the change of colour inversion for that bottom bar... if even any access at all? Maybe purely at the mercy of iPadOS bugs / quirks regarding that bar!

**Comment by mithrendal** [comment]
Hehe nice finding … vAmigaWeb does not directly sets the color… I tested a bit more … apparently iPadOS adapts the color of the bottom bar according to the background color on which the bar is drawn. You can test this when loading a dark game and then e.g. kickstart 1.2 white boot screen … you will see that it adapts … in your case it is a sort of in the middle gray …  maybe it is not sure whether going dark or white in this case 😀 …

**Comment by aZtOcKdOg** [comment]
Nice breakdown! Yes ok strange... there is nothing different between those 2 WB screens apart from an 
ADF inserted in one!

Strange!
