### ISSUE TITLE
Cannot load vAmigaWeb in iFrame if on same domain (Chromium specific?)

### ISSUE THREAD

**Issue by PTz0uAH** [vAmigaWeb/vAmigaWeb#187]
Hoi @mithrendal I am testing vAmigaWeb inside an iFrame called from my TAWS demo-site.. and ran into some major problems..

This does not consider using Firefox/Edge.. those browsers loads the emulator correctly even if embedded inside a window inside TAWS..
 
Since I started developing a custom Chromium embedded browser (build with Delphi/Lazarus CEF4DELPHI).. with support to embed the latest Chrome core.. I thought lets make TAWS also work for Chrome/Chromium (the serial port) but the vAmigaWeb emulator does not kick in.. strangely the external (from my perspective) hosted vAmigaWeb@github does work flawless and starts almost instantaneous..

The emulator works fine if the address is called directly outside TAWS without iFrame..

Now at first I thought it was a CORS thing but I did some reading and it could be very well possible that Chrome/Chromium needs to set a cookie "samesite=none" and "secure" before sending a request considering vAmigaWeb inside an embedded iFrame.. but I have no idea where to configure this.. (not sure if this is ueberhaupt the case)..

The TAWS test site is running from "/TAWS/" and when I click on an ADF file.. vAmigaWeb is called from "/TS0CA/#" and hangs forever.. with a spinning wait indicator.. and no control over vAmigaWeb what so ever..

Do you perhaps have an idea how to get it to work with Chromium/Chrome.. in other words.. am I missing something obvious or can I do something at vAmigaWeb server side or is the problem Chrome specific..?

To replicate the problem using Chromium/Chrome please look at http:SLASHSLASHtsocaDOTamigoxpeDOTnet (redirects to secure domain) and try to start vAmigaWeb or an ADF demo..

**Comment by mithrendal** [comment]
at first I only saw a black screen ... then hitting reload twice it started ... then when I click a demo disk it spawns vAmigaWeb but the mount button shows no reaction... I will have tomorrow a look into the debugger ...

**Comment by PTz0uAH** [comment]
while TAWS is initializing it is loading my huge test splashscreen.. this takes a couple of seconds and might show a black screen.. after that TAWS is coming up and calculates the directories on the virtual AmiGoNET harddrive.. which can also take a while depending on the number of files to index.. the server is not very fast..

the ADF links are on the "RAMDISK" and if you open the folder AmiGoXPE/TSOCA/vAmigaWeb there are 2 versions to start vAmigaWeb1 starts the self-hosted emulator and vAmigaWeb2 starts your github-hosted vAmigaWeb.. the latter works fine.. the self-hosted one does not start with Chromium/Chrome..

did you find any clue in the debugger?

**Comment by mithrendal** [comment]
both versions do work here in latest chrome for mac version 118.0.5993.117 (official build) (arm64)

so I can't know what is wrong on your local system. 

`hint` open javascript console and paste here what it is complaining about, also browsers network panel could be helpful...

**Comment by PTz0uAH** [comment]
After comparing the version of your CHROME and my CHROMIUM.. it became clearr..

My old configuration of the CHROMIUM dev environment was cef_binary_115.3.11+ga61da9b+chromium-115.0.5790.114_windows32 so I updated the CHROMIUM core to cef_binary_118.6.9+g7e73645+chromium-118.0.5993.119_windows32 and for convenience also the latest CEF4DELPHI.. (still using oldschool Delphi7)..

Now it seems to work as expected so it was very likely a CHROMIUM anomalie which got resolved in the latest versions..

Thanks for pointing out to the version of the Chrome you used..

**Comment by mithrendal** [comment]
looks like the browser can not allocate the requested wasm memory and also the ArrayBuffer in your backend_ds.js file. 

make a breakpoint inside your backend_ds.js file where it fails to execute 

new ArrayBuffer(B)

and check how big variable B is.

BTW: what is backend_ds.js ?

**Comment by PTz0uAH** [comment]
it seems I have some  interference from sections within TAWS I thought were disabled..

I cleaned up the TAWS code from any backend/dorment hippoplayer / modplayers,, and narrowed it down to the following debugscreen.. the missing png's can be ignored so it comes to the initialisation of vAmigaWeb..

Maybe I should update vAmigaWeb too?
![taws_debug3](https://github.com/vAmigaWeb/vAmigaWeb/assets/87427309/8da625a8-0781-4e35-a959-c79f52813324)

**Comment by mithrendal** [comment]
it can not allocate memory, i.e. the browser does not have access to at least 400MB memory or is not willing to give that amount of memory ... I am sure you are on a system which has enough memory free since the more basic chromium works ...

**Comment by mithrendal** [comment]
>and GPU acceleration etc..

you can enable gpu rendering with the following call param

https://vamigaweb.github.io/#{"gpu":true}

**Comment by PTz0uAH** [comment]
> you did say in the beginning that the version at https://vamigaweb.github.io/ works ... is that still the case ?

as vAmigaWeb2 is pointing to your url the following debugwindow indicates that that link works..

![taws_debug4](https://github.com/vAmigaWeb/vAmigaWeb/assets/87427309/8f27a751-585d-41c6-9538-e4095137a6ad)

**Comment by mithrendal** [comment]
that is really strange ... I mean why should a samesite web app have less privilege in getting some memory than a third party web app ?

what is the memory settings when you link vAmigaWeb ? is it the default 320Mb with autogrowth like in the regular version ? Or did you have increased the memory ?

**Comment by PTz0uAH** [comment]
> what is the memory settings when you link vAmigaWeb

what do you mean.. I just used the "prestine" vAmigaWeb binary distri from the vAmigaWeb github.. so I did no special compilation..

one thing that shows in the debugger.. vAmigaWeb1 is hanging yet thesettings-GUI-interface shows all kind of non existing drives..

also the kickstartbutton and the drive buttons do not work.. that's also strange..

![taws_debug5](https://github.com/vAmigaWeb/vAmigaWeb/assets/87427309/b93ff522-c7d3-44a5-bc23-dbf36f94e4a6)

**Comment by mithrendal** [comment]
> I just used the "prestine" vAmigaWeb binary

ah ok I thought you maybe build it yourself and pushed the initial mem requirements a bit too high... but that is not the case then

that it shows all kinds of drives and so on is because it has been crashed in early bootup and did not yet had the chance to configure all these buttons correctly -- because of the out of memory error --

**Comment by PTz0uAH** [comment]
well I've updated to the latest.. cleared the cache and same result..

![taws_debug6](https://github.com/vAmigaWeb/vAmigaWeb/assets/87427309/cfb71acb-da65-4d15-b8e5-d8d6df9ec8e2)

**Comment by PTz0uAH** [comment]
Thanks for the effort..

I 've also contacted the developer of CEF4Delphi and he suggested my Delphi7 conversion of the more complex Chromium browser could be buggy although working partly..

To rule out any 32bit anomalies he suggested to use Lazarus to compile the "MiniBrowser".. a same more complex Chromium example and that turned out to be the confirmation.. the Delphi7 variant is causing the trouble..

So running with the same Chromium core files for win32 it runs like a charm..

![lazarus_minibrowser_win32](https://github.com/vAmigaWeb/vAmigaWeb/assets/87427309/7e465267-d1ed-427f-b333-0fd9a8ca11b3)

The Delphi7 bug is still nagging me but at least I have an alternative to build my custom browser.. and neither vAmigaWeb nor TAWS is to blame..

Let's hope now I can focus on the serial fun laying ahead..

Another good thing is my AmiGoDOS on Chromium already showed a massive amount of AROS debug info spawned via the serial port which indicates that the serial part works fine.. (which might also explain why booting the AROS rom feels so slow..)

Cheers..

**Comment by mithrendal** [comment]
nice finding, I close then
