### ISSUE TITLE
When using a HDF with WB the filedates are wrong

### ISSUE THREAD

**Issue by PTz0uAH** [vAmigaWeb/vAmigaWeb#188]
Hoi @mithrendal 

It seems there is no vAmigaWeb option for keeping the time.. so at start vAmigaWeb machine runs in the past..

I could not find an option to sync the time at vAmigaWeb start.. if using a productivity environment..

![timebug](https://github.com/vAmigaWeb/vAmigaWeb/assets/87427309/a6d53473-545b-42e0-97d8-6f3005d535ef)

**Comment by mithrendal** [comment]
I will have to check the RTC component why it does not deliver the current time...

https://github.com/vAmigaWeb/vAmigaWeb/blob/main/Emulator/Components/RTC/RTC.h

**Comment by mithrendal** [comment]
the RTC seems to work

<img width="687" alt="image" src="https://github.com/vAmigaWeb/vAmigaWeb/assets/17108995/6642e3b4-4b6e-4b42-a8b1-18051b5dce8f">

@PTz0uAH did you maybe miss to load the clock in the workbench startup-sequence ?

**Comment by PTz0uAH** [comment]
@mithrendal  You are right!

On my backup HDF which was autoconfig due to the blizzard board I use I never had to adjust the clock manually..

I adapted the Startup-Sequence and now it's fine.. seems stepping down from a luxury position needed some re-reading of the manual..

Thanks!
![timebug_solved](https://github.com/vAmigaWeb/vAmigaWeb/assets/87427309/c69f0b63-6aca-4e09-a512-32dcc85514e0)

**Comment by aZtOcKdOg** [comment]
Hmmm... I am having this issue atm too and strangely I can definitely return the correct time / date after using the command 'setclock load' in cli... but placing the code in startup-sequence returns the incorrect time and date (1970) and without it in the startup-sequence the date returns as 1994...

Saving the time / date using 'setclock save' or using the OS doesn't seem to stick either.

Any ideas what I may be doing wrong? Thanks!

**Comment by mithrendal** [comment]
thanks mate ... I will have to retest this...

I am currently at releasing vc64web 5.0 ... after that I will check this issue again

**Comment by aZtOcKdOg** [comment]
...using 'SetClock LOAD' in the startup-sequence seems to work fine now!

Thanks for the tag in the recent post as I had not checked this for a while!

Great \o/

**Comment by mithrendal** [comment]
just tested kickstart 3.1 and plain workbench 3 without setclock command in startup-sequence   ... that extra `SetClock LOAD` is no longer necessary, because the kickstart loads the time and date from the RTC clock automatically on startup

**Comment by aZtOcKdOg** [comment]
Also tested and the correct time/date is now shown in DirOpus4!
(without using setclock in startup-sequence)

Nice
