### ISSUE TITLE
iPad Keyboard Issue

### ISSUE THREAD

**Issue by aZtOcKdOg** [vAmigaWeb/vAmigaWeb#193]
Hi,

In portrait orientation iPadOS 17.2 the keyboard is cutoff on the right hand side (non responsive to device width?)

![image](https://github.com/vAmigaWeb/vAmigaWeb/assets/64781882/c5441341-b935-4570-98aa-521f3b9629db)

**Comment by mithrendal** [comment]
Hi @aZtOcKdOg 

welcome to the new designed virtual keyboard 😎 the old is gone and the new grid based css is here !

>In portrait orientation iPadOS 17.2 the keyboard is cutoff on the right hand side (non responsive to device width?) 

The size is calculated  intentionally that way. It is responsive to whatever is side of the device is larger: width or height

In other words … it looks for the largest dimension X or Y and then calculates the full keyboard size to it no matter in which way you hold the device.

I could have made it also always responsive to the horizontal side i.e. width only. The result on devices with very tiny screens like iPhone would be that it would then also try to scale the full keyboard into the portrait mode width which would be too small to be usable. 

The better trade off for my thinking was to always go to the largest side in full and to clip/scroll the keyboard on the smaller side …  But I am open to better ideas 

Here is the current css function  (watch the max(100vwm 100vh))


```css
—keycap_size: calc(calc(calc(calc(calc(max(100vw, 100vh) - 2cm) / ${columns}) * 4) - 3px) * var(--keycap_zoom))
```

**Comment by mithrendal** [comment]
You find two new keyboard scaling positioning params in the settings

![IMG_0005](https://github.com/vAmigaWeb/vAmigaWeb/assets/17108995/790cb86b-8b68-4f59-80d9-2a9eac8eb273)

with them you can enlarge the size in portrait mode

**Comment by aZtOcKdOg** [comment]
I will check that out!

I also meant to say LOVE the new keyboard!
Looks and feels great, I will check those settings and report back- thanks for the detailed breakdown as always (very much appreciated)

Great work!

**Comment by aZtOcKdOg** [comment]
Nice! Ok so at the lowest keycap size .70 it fits perfectly in portrait mode and appears as expected!

The bottom margin is an excellent addition as the spacebar and bottom mod keys can be well away from the bottom edge- most excellent!

I notice that often keypresses remain stuck on (ie press down arrow or spacebar and the cursor will continue to repeat register inside emu- this has been happening for a while but it seems to happen in other emus so I didn't report but thought I better mention)

Also:
I have noticed since perhaps 2 updates ago that it often takes 2 presses for a button like DF0 + or HD0 + etc to 'register' when inserting media- I feel there is a time length for a delay before a button registers? (this behaviour often happens with anything web based using touch though but I wonder if there is a poll length ie touch register onclick >x ms etc?)

**Comment by mithrendal** [comment]
>In portrait orientation iPadOS 17.2 the keyboard is cutoff on the right hand side (non responsive to device width?)

@aZtOcKdOg  you were right 😎... on big screen devices the keyboard should at keysize=1.0 exactly fit the entire width, regardless of portrait or landscape... 

to make it behave responsive I added a media query with one breakpoint at max-width 511px. Everything above like iPads and foldable Phablet will at `keycap site = 1.0` exactly fit the width of the screen. 

Smaller sized devices like phones and other small devices will not try to fit it exactly when the width is below 512px (in portrait) because the keys would just be too small for the full keyboard. Instead they will increase the key size (as if it would be rendered on the larger side) the keyboard is scrollable.

new version is online ... set key size back to 1.0 or even less if you want the left and right margin  of the keyboard use as a mouse pad

**Comment by aZtOcKdOg** [comment]
Awesome, came straight here after update pushed to app! Great work (ahh nice... breakpoints ofc! clever!)

Thanks!

**Comment by mithrendal** [comment]
Added more keyboard settings for haptic and sound feedback and also for transparency

![IMG_0013](https://github.com/vAmigaWeb/vAmigaWeb/assets/17108995/4ea198a9-41af-44d7-8b34-925e0f80b89d)

**Comment by aZtOcKdOg** [comment]
That opacity option is great for coding! Very useful for games too ofc :)

I had a suggestion / query / request (maybe):

The keycaps and layout are true to original Amiga but the left shift key is quite narrow even in landscape. It is really hard to hit when editing copy / coding- I wondered if a perhaps a toggle is possible for an 'alt' layout like this:

Original:

![image](https://github.com/vAmigaWeb/vAmigaWeb/assets/64781882/841163d7-514b-4e3e-bf16-598ee26777b4)

Alt:

![image](https://github.com/vAmigaWeb/vAmigaWeb/assets/64781882/ece3c066-9624-4f08-b31c-34ffc3a43bb0)

So the new left shift key would be:
current width + spacing / pad + keycap width
(to keep the same relative spacing and layout)

with the '> <' key moved to the end of the previous row of keys (under enter key)

Also: I remembered that the original Amiga keyboard has left justified 'arrow' gfx on the shift keys with a slight pad
(I mention this if of visual interest / even feasible with the setup of css grid style etc)

Thanks o/ G'day from Australia btw and thanks for the great updates as always!

**Comment by mithrendal** [comment]
great lets make a new issue for a toggle US / INTL virtual keyboard ...
