### ISSUE TITLE
Insert media eg DF0 popup touch also registers as LMB in emu...

### ISSUE THREAD

**Issue by aZtOcKdOg** [vAmigaWeb/vAmigaWeb#196]
When insert media popup for DF0 etc (bottom screen) is touch selected it also registers as a left mouse button press inside the Amiga emu; meaning inserting a disk can also accidentally select or draw pixels in DPaint etc

(Sorry if already explained / posted - just wanted to check if this was a new behaviour or a bug)

-Thanks!

**Comment by mithrendal** [comment]
Good find ! Will repair

**Comment by aZtOcKdOg** [comment]
Actually seems all selector overlay modals / popups (eg Settings) click through as LMB with touch

**Comment by mithrendal** [comment]
Fixed the annoying touch pass through in

- Drive selector
- Settings
- top nav bar

**Comment by mithrendal** [comment]
fixed button pass through leakage in reset dialog adfdae6349b93ec9024a15a36a00fbd286ae31df

in upcoming version v2.6
