### ISSUE TITLE
vAmigaWeb runs on Apple Vision Pro 

### ISSUE THREAD

**Issue by mithrendal** [vAmigaWeb/vAmigaWeb#199]
impressions...

<img width="1065" alt="VisionPro_runsAmiga" src="https://github.com/vAmigaWeb/vAmigaWeb/assets/17108995/2d27f585-70d6-486c-a679-694cbf3859a8">

![Simulator Screenshot - Apple Vision Pro - 2024-02-03 at 23 38 48](https://github.com/vAmigaWeb/vAmigaWeb/assets/17108995/ec646b74-1d99-4548-a201-a10dcb9401fe)

**Comment by mithrendal** [comment]
<img width="918" alt="Bildschirmfoto 2024-02-04 um 13 45 04" src="https://github.com/vAmigaWeb/vAmigaWeb/assets/17108995/fb60cd2f-733b-44f1-90ec-3fb72f364baf">

<img width="918" alt="image" src="https://github.com/vAmigaWeb/vAmigaWeb/assets/17108995/58809a10-c399-4747-ac15-fe286e5cfa3c">


<img width="918" alt="image" src="https://github.com/vAmigaWeb/vAmigaWeb/assets/17108995/0eaae270-6779-407a-b478-a141854f28a8">

**Comment by mithrendal** [comment]
<img width="925" alt="image" src="https://github.com/vAmigaWeb/vAmigaWeb/assets/17108995/8b3ebb35-524f-4dc1-b6e7-b07464f27f48">

**Comment by warpdesign** [comment]
Is that a true pancakes recipe? I need to test that one :)

**Comment by mithrendal** [comment]
> Is that a true pancakes recipe? I need to test that one :)

Yeah … but only for a single person and also a bit too simplistic…

When you are done with it you might try this one … more delicate and up to 400 of your friends can have a good meal from it… 

**Baked Camel (Serves 400)**

500 dates
200 plover eggs
20 two-pound carp
4 bustards, cleaned and plucked
2 sheep
1 large Camel
seasonings

Dig trench. Reduce inferno to hot coals, three feet in depth. Separately hard- cook eggs. Scale carp and stuff with shelled eggs and dates. Season bustards and stuff with stuffed carp. Stuff stuffed bustards into sheep and stuffed sheep into camel. Singe camel. Then wrap in leaves of doom palm and bury in pit. Bake two days. Serve with rice.

**Comment by mithrendal** [comment]
![](https://vamigaweb.github.io/doc/images/vision_pro_vamigaweb2.png)

**Comment by flashbackcz** [comment]
WOW! 

You must be really mad! (;

I really like this. I just miss the head thing. :DDD

Can I use your photos for the news site? I would put your ownership on all the photos and add a github link.

> <img alt="image" width="925" src="https://private-user-images.githubusercontent.com/17108995/302109868-8b3ebb35-524f-4dc1-b6e7-b07464f27f48.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDc2NjI0NDUsIm5iZiI6MTcwNzY2MjE0NSwicGF0aCI6Ii8xNzEwODk5NS8zMDIxMDk4NjgtOGIzZWJiMzUtNTI0Zi00ZGMxLWI2ZTctYjA3NDY0ZjI3ZjQ4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMTElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjExVDE0MzU0NVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTlmODc4ODBjNzZiMmM0YTYxNmU3NDMyZjE2NGMwMTE2NGMyMWRjYjU3YjBlNzgwNmM3Y2FkNzEwYzhmNzM1YjImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.lngPBC_z2O2n1_vmdfTZpWoGqChLbRHCuovVoE6FLd4">
> **use case** `cooking in the kitchen`
> 
> * reading recipes in Amiga workbench’s `Notepad v2.0`
> * using Amiga Workbench `Clock v2.1` setAlarm function for timer when pancakes are done…

**Comment by mithrendal** [comment]
>Can I use your photos for the news site?

@flashbackcz sure mate do with them what you like 😎

as far as the "baked camel recipe" is concerned ... it is taken from the excellent book ["water music"  written by TC Boyle ](https://a.co/d/89CUspn)

**Comment by flashbackcz** [comment]
> > Can I use your photos for the news site?
> 
> @flashbackcz sure mate do with them what you like 😎
> 
> as far as the "baked camel recipe" is concerned ... it is taken from the excellent book ["water music" written by TC Boyle ](https://a.co/d/89CUspn)

As you wish. (;
I've already written it, the article will come out on Thursday (I'll post the link then). I've fleshed out your idea into a little story..

**Comment by flashbackcz** [comment]
@mithrendal I hope you like it. (:

Link (in Czech, but you can translate it via Google) - https://retro.flashback.cz/novinky/emulator-amiga-apple-vision-pro/

BTW: In the next few days I will publish an article about vAmigaWeb.

**Comment by mithrendal** [comment]
> In the next few days I will publish an article about vAmigaWeb

To be able to install vAmigaWeb as PWA on home screen of iPhone / iPad via share button is incredible … especial when given the fact that apple tries to keep all emulators away from its App Store…

When I discovered that back then doing it first for my other emulator vc64web I was totally freaking out 🤩 … see here 

https://github.com/vc64web/virtualc64web/issues/40

The vc64web is also nice ❤️, it is connected to the CSDb (Commodore Scene Database) and you can run literally everything that was made for that machine such as demos from it by a click without downloading any file on the host device…. (Scene browser is started by clicking snapshots browser icon from menubar)

**Comment by flashbackcz** [comment]
> Very funny article ! 😂
> 
> > In the next few days I will publish an article about vAmigaWeb
> 
> To be able to install vAmigaWeb as PWA on home screen of iPhone / iPad via share button is incredible … especial when given the fact that apple tries to keep all emulators away from its App Store…
> 
> When I discovered that back then doing it first for my other emulator vc64web I was totally freaking out about it🤩 … see here
> 
> [vc64web/virtualc64web#40](https://github.com/vc64web/virtualc64web/issues/40)
> 
> BTW: The vc64web is also nice ❤️, it is connected to the CSDb (Commodore Scene Database) and you can run literally everything that was made for that machine such as demos from it by a click without downloading any file on the host device…. (Scene browser is started by clicking snapshots browser icon from menubar). Try that one with https://vc64web.github.io
> 
> They have also demos with glasses …
> 
> Hang on I will look one up for you … https://vc64web.github.io/#https://csdb.dk/getinternalfile.php/253132/ALD_50_Shades_of_Zardax.prg (when it starts wait a bit its a c64 which needs to initialise … and click anywhere into the canvas to enable the music)
> 
> They are shareable with that little built in share button from the PWA app
> 
> ![IMG_0065](https://private-user-images.githubusercontent.com/17108995/305101841-78e519a5-cb8c-46b0-9c11-3f07cffc90f9.jpeg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDgwMTM0NzAsIm5iZiI6MTcwODAxMzE3MCwicGF0aCI6Ii8xNzEwODk5NS8zMDUxMDE4NDEtNzhlNTE5YTUtY2I4Yy00NmIwLTljMTEtM2YwN2NmZmM5MGY5LmpwZWc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMjE1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDIxNVQxNjA2MTBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT02NDkwNDEyOGE3ODVhMDU4MzBhZjQxNjk3MzA4N2IxNzYwNmYwZWIxYmY5MjM2MWRhZTRhNzY0YWJkNzE3YTNkJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.38OveC9nZXmbwqXBRftUxjyLanC6AH53H1ru9alOjMs)
> 
> Thanks to these two emulators the Apple Vision Pro has a vast library … literally thousands of application and games ready to use right from the beginning … without that the offered software on that expensive Apple glass would be really meagre …

I plan to describe both emulators in more detail and then report on the new versions. (:

Thanks for the additional information. 

I have to try the C64 version on my ipad. Then a connected joypad via bluetooth might work there, right?

**Comment by mithrendal** [comment]
> Then a connected joypad via bluetooth might work there, right?

Just pair your XBox Controller or Playstation Controler with the iPad/iPhone …   

1. pair up to two of them via iOS/iPadOS bluetooth settings … 
2.after you have done that, start vAmigaWeb / vc64web and select them into port1 or port2
