### ISSUE TITLE
Random Cannot Save Snapshot / ADF / HDF

### ISSUE THREAD

**Issue by aZtOcKdOg** [vAmigaWeb/vAmigaWeb#239]
After some short usage, often I cannot save the HDF that I am using and the 'hd in dh0' (save media) button becomes unresponsive in the 'Save Snapshot to Local Browser Space' dialog.

I have recently been able to see these 2 errors (images below) when this issue occurs while accessing 'Save Snapshot' and the browse snapshot dialogs respectively:

![image](https://github.com/vAmigaWeb/vAmigaWeb/assets/64781882/fbf08ac9-e6d0-4dc5-96c4-284a5f3ccdb3)

![image](https://github.com/vAmigaWeb/vAmigaWeb/assets/64781882/8d644e94-12a2-4be7-8496-83f5c3820291)

I wonder if there is a fixed cache being allocated / used / referenced when saving a HDF (and overwriting the file) in the iPadOS filesystem?
It seems to happen after some use and after a few HDF file saves...

**Comment by mithrendal** [comment]
Ok, I am start to looking into this one now...

**Comment by mithrendal** [comment]
bug found... 

on export / saving the disk I do clone the disk for exporting but I forgot to free the allocated memory after wards... i.e. on hitting the export button a few times with a large HDF it allocates new memory with every export and never frees it. It gets out of memory very quickly.

**Comment by mithrendal** [comment]
fixed version is online... it deletes the cloned disks (HD or floppy) from heap memory after export is finished.  

@aZtOcKdOg  thanks for reporting this one 👍
