### ISSUE TITLE
Paradox-DesertStrike on whdload.de

### ISSUE THREAD

**Issue by mras0** [vAmigaWeb/vAmigaWeb#252]
Probably not a vAmigaWeb issue, but I just tried the new embedded emulator for the (current) top entry on whdload.de (https://www.whdload.de/ctros/Paradox_DesertStrike.html) and it doesn't work (after decrunch the bitplanes just roll). Tried changing a few settings (like chipset and mem) to no avail. Perhaps something @wepl has to look at?

Did get me thinking that perhaps (in the far distant future) the UI when embedded could benefit from some restricts? Like ejecting dh0 is probably not going to be beneficial. If I change the settings does that affect other embeds on the same site? Just this one?

Not a major concern or anything, just though I'd mention it since this is a great feature enabled by vAmigaWeb :)

(Cracktro on it's own seems to work with at least older version of plain vAmiga and WB1.3 BTW)

**Comment by wepl** [comment]
I'm in contact with Fabio who has updated the install on my request because there was different problem before preventing it to run in vAmigaWeb.
The question if settings affect other embeds on the same site also puzzled me too.

**Comment by mithrendal** [comment]
I am currently on vacation on phone only … no computer with me. 

I provided @wepl with a startup hook where he can overwrite all user selected settings. This hook is executed whenever the web player is invoked on whdload web page.

After loaded (i.e. hook has been executed) and you adjust the settings these settings should be activated then until the next respawn of the vAmigaWeb player where they will be overwritten again by whatever @wepl  decides in the hook code.

In theory it should behave likes this. 

PS: maybe the cracktro needs another kickstart ? @wepl and me have found a way that lets the player ask the user to select cbm kickstarts before it is spawned.

**Comment by wepl** [comment]
Fabio told me he has tested on FS-UAE emulating an Amiga 600 with HD (KS 2.0, CPU 68000) without problems.
Maybe vAmiga behaves different here?

**Comment by mras0** [comment]
@wepl Could you share the hdf that's generated? Then I'll see if I can spot something..

**Comment by mithrendal** [comment]
@mras0 you can just export 

<img width="679" alt="image" src="https://github.com/user-attachments/assets/77550b59-8824-4bb1-b9f9-4d27a2df617c">

**Comment by mithrendal** [comment]
@mras0 dragged the exported hdf file into the MacOS version of vAmiga v2.6.2  

<img width="910" alt="image" src="https://github.com/user-attachments/assets/585abc76-2b80-4fc5-9bf9-d56cc05423c8">

can someone drag it into WinUAE ?

**Comment by mras0** [comment]
Ah, thanks! Didn't think to look in the snapshot menu. Enjoy your vacation.

I see the same behavior in WinUAE 5.3.0 with A600 quickstart (best compatability). Works if I turn off cycle exact.

It's stuck in Level6 handler:
```
00080318 2f0e                     move.l a6,-(a7)
0008031a 4df9 00df f000           lea.l $00dff000,a6
00080320 3d7c 2000 009c           move.w #$2000,(a6,$009c)
00080326 4a6e 0002                tst.w (a6,$0002)
0008032a 2c5f                     movea.l (a7)+,a6
0008032c 4e73                     rte  == $000802c2

INTENA: $602c ($602c) INTREQ: $2020 ($2020)

B: CRA 00 CRB 00 ICR e4 IM 04 TA ffff (ffff) TB ffff (ffff)
   PRA f8 PRB ff DDRA c0 DDRB ff
   TOD 012d2c (000010) ALARM 000000 --
```

So unexpected alarm interrupt from CIAB?

**Comment by mras0** [comment]
@wepl CIAB.IM=04 (indicates alarm interrupt enabled) is set on entry to slave ($000800da w/ A600 QS), doesn't seem like that should be right according to https://www.whdload.de/docs/autodoc.html#SlaveOverview ? (The above handler routine is also part of slave)

BTW I've just updated https://github.com/mras0/vAmigaSDL/ in case you want to check something on desktop (I don't have a Mac either). It is not good for debugging as there is no built-in debugger, but if it works there it will 99.9% sure work in vAmigaWeb.

**Comment by wepl** [comment]
@mras0 thanks a lot for the analysis!
whdload docs are wrong, mask was never initialized and had their value from the os
I will release a fixed whdload and hope that this change does not break too much other installs
with the fixed whdload the cracktro runs now

**Comment by mithrendal** [comment]
just added a Activity / DMA Debugger icon to the player bottom bar. Next to the zoom icon. On click it toggles the bus activity monitors. Clicking on a particular activity  monitor toggles the DMA debugger. 

<img width="664" alt="image" src="https://github.com/user-attachments/assets/22c2c45b-b66f-49aa-884b-752db383132d">

in this case above blitter dma debugger is  enabled.

**Comment by wepl** [comment]
nice addition, thanks 😄 
what would be useful for me anytime in the future: a grab picture function (but ATM I have anyway no time to put pictures in the player background)

**Comment by mras0** [comment]
> @mras0 thanks a lot for the analysis! whdload docs are wrong, mask was never initialized and had their value from the os I will release a fixed whdload and hope that this change does not break too much other installs with the fixed whdload the cracktro runs now

Glad you got it sorted. Seems really unlikely that someone would be relying on OS set mask, but of course you never know, though it seems like they shouldn't. 

> just added a Activity / DMA Debugger icon to the player bottom bar. Next to the zoom icon. On click it toggles the bus activity monitors. Clicking on a particular activity monitor toggles the DMA debugger.
> <img alt="image" width="664" src="https://private-user-images.githubusercontent.com/17108995/367583253-22c2c45b-b66f-49aa-884b-752db383132d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjY0MjQ2MjgsIm5iZiI6MTcyNjQyNDMyOCwicGF0aCI6Ii8xNzEwODk5NS8zNjc1ODMyNTMtMjJjMmM0NWItYjY2Zi00OWFhLTg4NGItNzUyZGIzODMxMzJkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MTUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTE1VDE4MTg0OFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTc4MWQ2MDZhZGIyYWI4M2Q3NmRkODNkMzEwZjdhOGZmM2FmYWNhNzYxMjZiNTBkMjQ5MzA3ODAzYzlmZWJmNWUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.xuomI6sd5-2bOBvMHJ6HFzKUOEwjHTJnVk1SMA0beIs">
> 
> in this case above blitter dma debugger is enabled.
> 
> maybe I should add a warp button now too 🫡

Nice! Great addition.

Closing this issue as things have been resolved, and it was never a vAmigaWeb issue to begin with :)

**Comment by mithrendal** [comment]
added a warp button next to the play/stop icon inside the players bottom icon bar...

>what would be useful for me anytime in the future: a grab picture function (but ATM I have anyway no time to put pictures in the player background)

you can write an action button for this .... I asked chatgpt to write it and it works

<img width="1130" alt="image" src="https://github.com/user-attachments/assets/26b56fca-c593-4f08-a33c-1594e2eedbca">


for this 5 liner script it is necessary to set the `video renderer` to `software` instead of `gpu shader` in the vAmigaWeb settings.

like this 
<img width="737" alt="image" src="https://github.com/user-attachments/assets/a7a96bdc-70cf-4442-b075-631f282106f8">


here is the 5 liner

```javascript
// Function to download the canvas content as an image
const dataURL = canvas.toDataURL('image/png');

// Create a link element
const downloadLink = document.createElement('a');
downloadLink.href = dataURL;

// Set the download attribute to specify the file name
downloadLink.download = 'canvas-image.png';

// Programmatically trigger a click to download the image
downloadLink.click();
```


copy an pic from an webgl context is also possible but with some more lines of code ... if necessary we could also asked chatgpt

**Comment by wepl** [comment]
but this way I get a scaled image from the browser, right?

**Comment by mithrendal** [comment]
The fully oversize screen buffer is clipped according to the setting `visible display area` and then copied 1:1 to the canvas which is adjusted to the same width and height as specified by that setting.

Scaling is only done afterwards by the browsers CSS engine so when saving the contents of the canvas it is still unscaled. 

Unscaled but clipped.
