### ISSUE TITLE
Desert Dream Issues

### ISSUE THREAD

**Issue by mras0** [vAmigaWeb/vAmigaWeb#3]
Hi,

First: Great job on the webport! 👍 This is just random feedback after trying it out quickly, so take it for what it's worth and close at your convenience.

I used what it identifies as Kickstart 1.3 rev 34.005 in Firefox 93.0 and Edge 94.0.992.50 on Windows 10 (Intel i7-8665U, 48G RAM, Intel UHD Graphics 620/Nvida Geforce MX250 laptop). Didn't change any settings.

I tested with Disk 1 of [Desert Dream](https://www.pouet.net/prod.php?which=1483) and noticed:

* If I changed tabs it just looped the current sound buffer (this maybe impacted the further tests. Emulation seems to be otherwise paused.
* General sound glitches. I'm pretty tone deaf, but there's something off. Sorry I can't be more specific, maybe it's replaying the same buffer twice? (I could maybe record it if you don't notice it). CPU usage isn't noticeably different when it happens.
* The emulation speed is off (missiles go through the space ship). I guess this is because it's based on an older vAmiga version (don't know how old, but https://github.com/dirkwhoffmann/vAmiga/issues/466 is still present :))
* The screen is cut short in the morphing dot sphere part before (1..2..3..4..12000 dots) (could be vpos $100)
* Wireframe tunnel after "Revolution" is missing (blank screen)

The last three are possibly because an old version of vAmiga was used, so just ignore that if it matches the desktop version.

**Comment by dirkwhoffmann** [comment]
@mras0: Thanks a lot for testing the emulator and reporting issues! 
@mithrendal: The first thing you should check are the compatibility settings. Does the web version run in Blitter level 2 and are the disk drives emulated with original speed? In addition, please check the Agnus revision. Make sure you don't use the old OCS revision.

**Comment by mithrendal** [comment]
upgraded to latest v1.0.7 vAmigaCore https://github.com/dirkwhoffmann/vAmiga/commit/77ef10505f0a1d213f9b525c35498752acd8b421

@mras0 can we close ?

**Comment by mras0** [comment]
Yes, looks like we're ready for part 2 (which requires mouse support to get to) 😄 

![image](https://user-images.githubusercontent.com/9952017/142469746-c75177b4-9922-4b6f-b66e-ce6426dcb11b.png)

**Comment by mithrendal** [comment]
@mras0 Cool 😎 then I am going to do it right now. Don’t know should I start with the touch mouse or the real mouse?  Touch for iPhone iPad etc. And real mouse for the computer mice.

**Comment by mras0** [comment]
I only have normal computers (that I test with anyway), so I can't help with the touch stuff. I recently added a (crappy) SDL backend for my own emulator: https://github.com/mras0/AmiEmu/blob/aa7b7a29f0d4b6230c12d2d14ce795196927ec1b/sdl_driver.cpp (but the relative mouse movement doesn't work correctly under WSL2, but maybe that's a windows issue). Still there might be something useful you can use. The keyboard codes (when you get to that part) comes from here: http://amigadev.elowar.com/read/ADCD_2.1/Libraries_Manual_guide/node0479.html

For demos (and test executables), just getting left and right mouse buttons to do something is fine, so I'd focus on that at first. You probably need some capture/release code for the mouse anyway, so that might be the first starting point.

**Comment by mithrendal** [comment]
I try with the real mouse first ... seems easier ... on javscript side there is the pointer lock API which is super simple and on the emulator side there is something called 

```
// Emulates a mouse movement

void setXY(double x, double y);

void setDxDy(double dx, double dy);
```

in the mouse object ...

so should be fairly easy... the more tricky part becomes the touch stuff because I have to emulate a trackpad and the right mouse click ...

**Comment by mithrendal** [comment]
@mras0 mouse support is online  we can check part2 😎... 


next we should do the trackpad mouse for touch devices ... I will look into it tomorrow
