### ISSUE TITLE
migrating from make to cmake build toolchain

### ISSUE THREAD

**Issue by mithrendal** [vAmigaWeb/vAmigaWeb#41]
we got now a separate branch https://github.com/vAmigaWeb/vAmigaWeb/tree/cmake to evaluate cmake

in order to build the main program just as usual we type 
```
make 
```
this creates the mainsdl.o object file

next we cmake the vAmigaCoreLib in a separate build folder
```
mkdir build 
emcmake cmake -S Emulator -B build
cd build 
make
cd ..
```
now we have the libvAmigaCore.a in the build folder 

to link that together and generate the wasm we type as usual
```
make bin
```
 
as a result we get the wasm file for the browser, in particular we get this three files

```
index.html
vAmiga.js
vAmiga.wasm
```

we start with 
./start.sh

upon start we get this 😬
![image](https://user-images.githubusercontent.com/17108995/147462870-bd36357a-e427-4989-8ba2-03268a478bec.png)

this is misleading and hides the real error because it is a highly optimized build, emscripten leaves out code checks and those stuff

lets enable debug symbols and assertions with `-g -s ASSERTIONS=2 `

when started in the browser it generates this message
![image](https://user-images.githubusercontent.com/17108995/147461751-a68e96fb-57ea-48f7-b065-a8e4f1913ae7.png)

if we now additionally add the linker parameter `-s SAFE_HEAP=1` 
we get this picture
![image](https://user-images.githubusercontent.com/17108995/147462766-37836eeb-486e-4435-b8af-03a34f7530d0.png)

when we switch over to pure handwritten makefiles and completely leave out cmake and manually generate a emulator_lib.a file on the very same code with

```
emar rcs emulator.a Emulator/*.o Emulator/*/*.o Emulator/*/*/*.o  
```
and link that manually build archive .a file to the mainsdl.o file and run it in a browser everything works like a charm

does anyone have an idea what is wrong here ?

@mras0 do you maybe have an idea why the cmake build segfaults at runtime ?

**Comment by mras0** [comment]
Looks like the same issue I ran into here: https://github.com/dirkwhoffmann/vAmiga/issues/611#issuecomment-984880739

When compiling against the vAmigaCore library you need to ensure that you have the same feature flags defined (in this case, you probably need to define SCREEN_RECORDER). It's easier to keep in sync if everything is compiled with CMake, since the flags are automatically propagated (if they're PUBLIC at least).

**Comment by dirkwhoffmann** [comment]
> you probably need to define SCREEN_RECORDER

Oh yes, that makes sense. I should merge in the Windows code for the screen recorder asap. Once this is done, we don't have to take care about different feature sets any more.

**Comment by mithrendal** [comment]
I only took out the screenrecorder in the 
`Emulator/CMakeLists.txt`

```
# Enable additional features on certain architectures
if(NOT WIN32)
#  target_compile_definitions(vAmigaCore PUBLIC SCREEN_RECORDER)
  target_compile_definitions(vAmigaCore PUBLIC GDB_SERVER)
endif()
```

which made it work ... 

@mras0 thank you 😅 that was really fast and precise !👍


the next step will be to learn now how to integrate the mainsdl.cpp also with cmake. I have to look some tutorials first about cmake I bet...😅

**Comment by mithrendal** [comment]
>It's easier to keep in sync if everything is compiled with CMake

@mras0 

I am completely new to cmake and had first some trouble to get it running with emscripten toolchain ... after hours of studying it I deleted all previously handmade makefiles 😎 and now we have a result which I am very happy with🙃 ...  ... nevertheless would you mind to have a look on it and do some code review ? Escpecially the base CMakeLists.txt  


to build and run vAmigaWeb locally, the following command sequence is now necessary
```

mkdir build
emcmake cmake -S . -B build
cd build 
make
make run

start a web browser and head to localhost:8080
```

**Comment by mras0** [comment]
Looks good to me 👍 

Optionally you may want to add `DEPENDS vAmiga` to your custom targets (run/publish) to make sure you have the latest version and can always just run `make run`.

I'd probably also create a `.gitignore` file for `build`, `index.html`, `vAmiga.js` and `vAmiga.wasm`.

**Comment by mithrendal** [comment]
@mras0 that's great now we can just call `make run` and everything is being build automatically 😎

```
mkdir build
emcmake cmake -S . -B build
cd build 
make run

start a web browser and head to localhost:8080
```

or without using make
```
mkdir build
emcmake cmake -S . -B build
cd build 
cmake --build . --target run

start a web browser and head to localhost:8080
```

I also added the generated files to .gitignore as you said ....👍
