### ISSUE TITLE
santa rocks on some windows machines with choppy gfx and sound

### ISSUE THREAD

**Issue by mithrendal** [vAmigaWeb/vAmigaWeb#42]
reported by an author of https://amiga-news.de website

[SantaRocks](https://www.lemonamiga.com/games/details.php?id=4589) is having difficulties on vAmigaWeb on some Windows machine, which otherwise do more demanding games just fine.

direct start link to SantaRocks 

for physical keyboard (directions with cursor keys, fire with space key)
https://vamigaweb.github.io/#{"AROS":true,"warpto":4600,"port2":true,"url":"/doc/media/SantaRocks.adf.zip"}

for touch devices (directions left half of the screen, fire right half of the screen)
https://vamigaweb.github.io/#{"AROS":true,"touch":true,"port2":true,"url":"/doc/media/SantaRocks.adf.zip"}

direct start links with parameter AROS=true means that it will start directly into the boot process of the media specified by parameter url , vAmigaWeb does not ask for rom configuration or anything else ... 

(it just loads a bit slowly from floppy ...  you must be patient 🤓)

**Comment by mithrendal** [comment]
it has been reported that the machine in question does just fine when using chrome but on latest edge and firefox gfx is choppy as well as sound

it runs fine on my windows laptop using edge as well as on my older macs regardless of the browser... 

see here a video of the windows machine and using edge version 94

**Comment by halle-saale** [comment]
This is a little video of the game showing how the music 'stumbles'...
In this case I used "Kickstart 3.1, Rev 40.063, July 1993, A500, A600, A2000" on Firefox 95.0.2 (64bit) under Windows 10 Pro on Intel(R) Core(TM) i3-2330M CPU @ 2.20GHz, with 4GB RAM.

If I instead use the AROS raplacement ROM it is the same.

https://user-images.githubusercontent.com/20752227/147723032-2805c970-ab4a-456a-ae1b-6ac3cb3d4fea.mp4

**Comment by mithrendal** [comment]
@halle-saale 
great video thank you very much ! 🤓 At least I can see your trouble now 

first

could you please do it again but this time with live debug enabled (you will find a switch for that under settings) 😬

what I want to look at now is the consumed audio_samples by the audio interface over the time ... and also whether there any downs in the FPS rate over the time


second
when the game is open and live debug enabled could you manage to place the windows task manager into the picture so that we can see the CPU pressure over time and also whether there are other tasks which are are demanding while emulation takes place.


In the meantime ...
 
I have installed the very same firefox on my windows laptop and do not any stumbling. 

Additionally I ran it on a very ancient flagship code named "the gandpa" a macbookpro which is from 2007 on firefox 78 without any glitches . Old grandpa can not upgrade to 95.0.2 ... too old. 😢

what you also told me was that you do not see this on other amiga titles right ? 
which would indicate that it is a game specific thing with vAmiga  🤔

and also that you do not see any stumble on chrome (but also on the chrome based edge browser)
which would indicate that it is NOT a game specific thing with vAmiga  🙄

I am curious for the next video which will show live log of performance and runtime statistics...

**Comment by halle-saale** [comment]
So, here is another video...
This time I stuck with the menu screen because also there the music was almost completely broken. Your guess could be right that it is due to CPU load because it was much more bad while loading the task manager and the video application...
  
https://user-images.githubusercontent.com/20752227/147804843-42f5165b-48a3-429c-9d3e-19797db561f3.mp4

**Comment by mithrendal** [comment]
concerning the taskmanager 

1.the process view tab is more interesting as it gives us information about other concurring processes here
2.what you also could do is Taskmanager->Option->Show Always on Top


I can see you have a lot of lost syncs in the live debug statistics that is because the "executed" speed goes below 50 Hz in the live debug. That could explain the stumbling ... 

So the issue here could be because of CPU pressure ...

But what makes me wonder is why is the sound muted over long passages ...  I will take a look at the sound output behaviour of vAmigaWeb under CPU pressure. 
In the end it is a consumer / producer problem ... the audio thread is requesting audio samples to feed the two channel 48Khz audio stream whereas the emulator is producing the data for this stream. The stream has to be continuous ... Here we see it is stuck at the emulator side (lost sync output in the live debug) still strange that we hear no audio at all in this case ... I will review the implementation of the audio output regarding this...


@halle-saale 
1. Hmm 🤔... do you also see lost syncs when you are NOT capturing the video ? 
2. could you make another video one with taskmanager process tab view ?
3. because the video capturing itself does some pressure on your machine, could you do the video capturing from outside e.g. with a smartphone ? Or maybe a photo is now enough... What I want to see is the performance stats in the live debug and the process view tab in the taskmanager... I think a photo is sufficient...
