### ISSUE TITLE
hide androids bottom navigation bar

### ISSUE THREAD

**Issue by mithrendal** [vAmigaWeb/vAmigaWeb#72]
@Vweber73

I found something how to remove the navbar 

https://eolsen.dev/posts/how-to-hide-the-navigation-bar-in-a-pwa/

I changed the display setting in the PWA manifest.json file from `standalone` to `fullscreen`.

Can you again save the PWA to your homescreen and see whether the bottom bar is removed ? I will check iOS ... The reason to install the app again is that the manifest file will be evaluated only on installation ... it does not update an existing PWA

**Comment by Vweber73** [comment]
I did that. Works perfectly :) thanks !

**Comment by Vweber73** [comment]
I think best would be to make this optional via an option. Seeing both bars (top with clock and battery level)! And bottom (virtual buttons) is not necessarily badw there is still a lot of real estate... Depending on what you want to do you may want this or not.

Actually as a status bar, I would love floppy disk sound and diode indicator ;)

**Comment by mithrendal** [comment]
yes ... later  🤤 ... I am a family father ... time is rare 😂 ... but this is all easy to do ... we will do it ...

**Comment by Vweber73** [comment]
Hey hey I am a father of 2 boys too, I know what this is ! No hurry, priority to your kids ! :)

Here is a full-screen photo for you :)

Cheers 
![image0 (1)](https://user-images.githubusercontent.com/92450215/165138598-c879b000-fb42-4eff-b21e-f5e2b4fdff67.jpeg)

**Comment by mithrendal** [comment]
that looks better without the bright bottom bar no ? But look you have still a bit reserve at the top ... there is still a reserve of 10% in vertical screen space. on your z3. What happens when you turn it to landscape ? on iOS the status bar which was there in portrait vanishes then ... what about android?

**Comment by Vweber73** [comment]
Here what happens in landscape with different configurations (w and wo keyboard and w and wo app menu).
Cheers
![Screenshot_20220425-194929_Chrome](https://user-images.githubusercontent.com/92450215/165145536-036c42f0-c27d-4dcd-87df-e5da1c9f41dc.jpg)
![Screenshot_20220425-194921_Chrome](https://user-images.githubusercontent.com/92450215/165145539-d57cc733-09d7-407b-a4d0-5f727e63d16b.jpg)
![Screenshot_20220425-194908_Chrome](https://user-images.githubusercontent.com/92450215/165145541-faecd7c8-52de-4962-a151-d3c109a22366.jpg)
![Screenshot_20220425-194855_Chrome](https://user-images.githubusercontent.com/92450215/165145543-a2ac9730-ecd9-47e2-a745-69df7e8da1b5.jpg)

**Comment by mithrendal** [comment]
was this the version with standalone setting ? or with fullscreen manifest setting ?

maybe we should leave it standalone and having the statusbar and bottom navbar in portrait mode, and when turning into landscape maybe it removes the status bars automatically ? In iOS regardless of standalone or fullscreen: portrait has always top statusbar and landscape does not show any extra status or nav bar

**Comment by Vweber73** [comment]
That was Fullscreen, the latest.
Yes, why not doing this, sounds good !
Cheers

**Comment by mithrendal** [comment]
ok could you test whether the display=standalone version has no status bar and no bottom nav bar in landscape ?

**Comment by Vweber73** [comment]
Ok but how ? I installed the new version on my home screen, so I don't have the old one anymore ?

**Comment by mithrendal** [comment]
on iOS I can install two different ... on android no ?

**Comment by Vweber73** [comment]
Doesn't seem so, at least with Chrome. The menu item "save app" is only here if I uninstall the app. Otherwise I have only "launch vAmigaWeb"...

**Comment by mithrendal** [comment]
Ok. I think we leave it fullscreen then? Without the bottom navbar? Why was your bottom navbar so bright color ? It was a bit too invasive … no? Without it looks not so distracting …

**Comment by Vweber73** [comment]
Well, since I have some extra space on top of the Amiga screen, it doesn't bother much to have the bottom line and even the top one... Not sure which choice is best, that's why I asked if it could be configurable. 
The bottom bar may appear bright on the photo, but it is not that bright on the phone, just normal...

**Comment by Vweber73** [comment]
Not sure if it is related, but now Interceptor first line is cut...
![Screenshot_20220425-225722_Chrome](https://user-images.githubusercontent.com/92450215/165174088-328c4634-0a98-4025-b7da-4283395469e2.jpg)

**Comment by mithrendal** [comment]
>Not sure if it is related, but now Interceptor first line is cut...

no it is not related to fullscreen ... I can reproduce it ...seems that calibration stopped somehow...  going to standard or narrow and again to borderless will continue calibration... I have to debug this after the real work ... has to do with some optimisation I guess which I made to calibration process in order to reduce the amount of screen area to be processed/analysed ... brand new stuff but still seems a bit buggy ... we will see 

regarding fullscreen/standalone:
please look in the vc64web which is still dispay=standalone and tell me whether when turned to landscape the status bar and bottom nav bar will be hidden or not ...

**Comment by Vweber73** [comment]
Great, thanks !
Here is vc64 in landscape.
Cheers 
![Screenshot_20220426-095149_Chrome](https://user-images.githubusercontent.com/92450215/165250090-dce3b232-5f9c-45e0-a160-d92d8a491b14.jpg)

**Comment by dirkwhoffmann** [comment]
> I see no options for that...

There is no NTSC option. vAmiga emulates PAL machines, only.

**Comment by dirkwhoffmann** [comment]
> Any plan to support NTSC manual

Right now, I have no plans to support NTSC. To emulate it correctly, long lines and short lines would have to be distinguished (on PAL machines, all lines have the same length which makes emulation a bit easier). Of course, it could be done, but I don't see a real benefit. I don't know of any interesting title which is available for NTSC, but not for PAL. The PAL market was much bigger and thus more important for Commodore back in the day.

**Comment by Vweber73** [comment]
Indeed ! But some titles designed for NTSC are slower and 16/9 looking in PAL mode... :)

**Comment by mithrendal** [comment]
>Here is vc64 in landscape.

ok then with display=standalone there is still the bottom nav bar ... so we better choose fullscreen... some others on android might not have such a big display as you ;-)

>Not sure if it is related, but now Interceptor first line is cut...

I just published an update 😎... please retry

**Comment by Vweber73** [comment]
Yes for the big display :)
For the new version, many thanks, works fine, except that... Transitioning live from standard to borderless is...well, surprising :)
Cheers
![Screenshot_20220426-221125_Chrome](https://user-images.githubusercontent.com/92450215/165384363-ab78eae4-a6cf-49c3-8f35-502aee59aec5.jpg)

**Comment by mithrendal** [comment]
Uh. I have not tested from standard to borderless 🥴

**Comment by mithrendal** [comment]
>Transitioning live from standard to borderless is...well, surprising :)

I think now with the plausible check and minimum heights or borderless it is much much better ... just pushed the new version update out 😎... what do you think ?

**Comment by dirkwhoffmann** [comment]
> Wouldn't NTSC be useful for it ?

Yes, it would. I don't want to argue against NTSC support, it's just that there are bigger fish to fry at the moment. I might add NTSC support at a later point in time. 

> what are the sprite layers stencil for exactly ?

This is mostly a debugging feature. It allows you to cut out certain graphics layers (e.g., certain sprites). When a sprite is cut out, the background (dark checkerboard pattern) shines through. I used this feature a lot to find out the sprite number for a given object. E.g., in this example I've cut out all sprites but the first two:

<img width="1044" alt="Bildschirmfoto 2022-04-27 um 19 58 40" src="https://user-images.githubusercontent.com/12561945/165590464-6763eac9-137c-442f-bdf2-a3fea77a6590.png">

**Comment by Vweber73** [comment]
Ah ok, many thanks !
Cheers

**Comment by mithrendal** [comment]
in vAmigaWeb you have also the possibility to program with little javascripts a **super weapon** within an action button ... for example did I include a AutomaticFire AI bot template which recognizes the enemy sprite in the game Archon (from freefall) it recognizes the enemy and according to enemies sprite coordinate shoots automatically at it...   

The sprite layer stencil helps you to identify the sprite number of your player sprite and the enemy sprite... then you can query per javascript give me  position of lets say sprite 1 and 4 and trigger automatically per script some joystick action like fire or moving up or down ...

**Comment by Vweber73** [comment]
Wow ! That's ultimated geekiness ! :) Not sure I want to go that road, but I admire the baldness of this !
Cheers

**Comment by mithrendal** [comment]
I think we can close as we are going now with display=fullscreen in the manifest.json file which hides android bottom nav bar
