### ISSUE TITLE
Disk switching

### ISSUE THREAD

**Issue by Vweber73** [vAmigaWeb/vAmigaWeb#74]
Hi Dirk,

I tried the Settlers.
Starting booting disk 3 (disk 1 is just the intro), so far so good, it asks for disk 2, I switch and press the mouse button, it keeps asking for disk 2. Is something wrong ? RetroArch/PUE has no problem with the same files...

Btw how does multiple drives work ? Put all disks in the same zip file, they are assigned to drive numbers in alphabetical order ?

Thanks and cheers

**Comment by mithrendal** [comment]
>it keeps asking for disk 2

I will look at it 

BTW: There is also a hd version of it ... at planet emu -> amiga hdfs 

>how does multiple drives work ? Put all disks in the same zip file, they are assigned to drive numbers in alphabetical order ?

currently only df0: and hd0: is working. whenever you mount a disk it goes into df0 and if you mount  hdf it goes into hd0 ... df0 and hd0 works in parallel e.g. you can insert a floppy disk and a harddrive at the same time. I plan for next month or so to do a mount selector or something like that to support df0 - df3 and hd0 - hd3

**Comment by Vweber73** [comment]
Oops, apologies Mithrendal ! I got confused about your identity :)

Many thanks for looking into the disk change issue. Yes, I know about the settlers hdf. It is not bootable, but since you can load both adf and hdf, I could successfully launch settlers booting with interceptor disk :)

Btw what about auto-off ? On my phone it comes very quickly when your are idle, a bit ennoying.

Also what is the "cinematic" screen option ? Couldn't see what it does...

Thanks and cheers

**Comment by mithrendal** [comment]
> I could successfully launch settlers booting with interceptor disk :)

cool ... workbench does it too ;-)


what did you mean with auto off? Do you mean the powersaving from the OS ? I am afraid that is not in my control ? Can you set this in androids settings ?

cinematix screen option make the picture wide ... wide as it goes ... thereby violating the correct aspect ratio ... it is meant to have all pixels used from a tiny phone ... that is no borders to the left and right

cinematic disabled
![image](https://user-images.githubusercontent.com/17108995/165855583-363783aa-f7cd-43d7-8315-60193e0d8137.png)

cinematic enabled
![image](https://user-images.githubusercontent.com/17108995/165855712-83c0900c-9d4d-49f0-a567-73dd0ec413b7.png)



I just tried disk switching in settlers ... it worked twice... when inserting the disk2 adf , but when I inserted the zipped disk2 then it did not work ... it did a reset instead ... I think somewhere I decided when placing a zip file then user wants to completely start over ... because I thought multivolume games files should all be in one zip e.g. all settlers files in one zip ... maybe I better should remove the automatic reset? ... will look for it ...  

can you send me the snapshot when it asks for disk2 ? Maybe I can then see whats wrong ...

**Comment by Vweber73** [comment]
Auto off: yes you can set this at OS level but also on app level. Cpcemu never goes off !

Cinematic: has no effect on my phone ! Maybe because the Z3 is big enough ? :)

Thanks for testing the switch. I noticed it works with KS 3.1, but not 1.3 !! I can send you the  faulty one after one failed attempt to switch disk but I have to find it, where is it stored ?

Thanks and cheers

**Comment by Vweber73** [comment]
I could download it, but it is 15mb, where can I sent it to ?

**Comment by Vweber73** [comment]
Here we go for the snapshot.
Btw I tried vAmigaWeb on my ipod touch, just to see how small is beautiful, and had the following problems:
1) Choppy sound, gets worse when you go to settings back and forth...
2) In Landscape mode touching the top bar to make the menu reappear, and first line menu when it is there, doesn't work. The second line does.
3) Borderless mode gets confused when switching from portrait to landscape, and vice versa, only partial screen display.
4) Leaving the app and coming back cuts the sound, doing it again restores it...

Thanks and cheers 

[Settlers, The (1993)(Blue Byte)(Disk 2 of 3)_snap4.zip](https://github.com/vAmigaWeb/vAmigaWeb/files/8589461/Settlers.The.1993.Blue.Byte.Disk.2.of.3._snap4.zip)

**Comment by Vweber73** [comment]
Here is the disk itself...
Ipod iOS version: latest, 15.4.1
[Settlers, The (1993)(Blue Byte)(Disk 2 of 3).zip](https://github.com/vAmigaWeb/vAmigaWeb/files/8589752/Settlers.The.1993.Blue.Byte.Disk.2.of.3.zip)

**Comment by Vweber73** [comment]
I have redone all of this... And it worked ! I don't get it, I tried many times yesterday and I am pretty sure it didn't work... I didn't choose the zip file, I know it resets the Amiga, I chose the adf, and it didn't reset, after a while it asked disk 2 again... Strange !

**Comment by mithrendal** [comment]
>I tried many times yesterday and I am pretty sure it didn't work...

1. the old version without borderless had a disk change detection bug ... which has been resolved ... but many days ago... maybe you still had the old version installed somehow ??

2. the disk change detection is dependend of the Amiga game/software. The detection code of a game needs some time between disk eject and disk insert (for some games up to 1.8 seconds AFAIK desert storm disk2 was the game with the longest time needs 1.8 seconds) maybe settlers needs 1.9seconds or so ? To verify try 10 times ... when we see some failures we should increase the disk swap time to maybe 1.9 or 2 seconds

**Comment by Vweber73** [comment]
I was always on the latest borderless version...
I will try again many times

**Comment by mithrendal** [comment]
>I will try again many times

thanks 😊 for more background on detection see

https://github.com/dirkwhoffmann/vAmiga/issues/156

**Comment by Vweber73** [comment]
On my ipod, it is not as bad... Once the battery is charged. It seems that vAmigaWeb drains the battery very fast, I had very little remaining when testing. After charge, the sound is correct, the rotation triggers less resizing errors, and I found that touching a bit below the icon manages to trigger the action in landscape. Still, when leaving / coming back to the app the sound disappears / reappears. Also the file icon does not always work...

**Comment by mithrendal** [comment]
>Once the battery is charged. 

I you enter battery saving mode ... iOS will reduce cpu clock rate to a fraction of normal operation speed thus resulting in as many time possible out there in the wildness with a operational phone ... this way doing emergency phone calls is still possible but calculations are severely slowed down ... especially on older devices... on most modern devices the degradation in clock speed does not matter as there is still enough processing left to calculate the Amiga

**Comment by mithrendal** [comment]
> when leaving / coming back to the app the sound disappears / reappears.

iOS does not allow any PWA execution while in background... therefore sound stops on leaving the app and continues when entering again...

**Comment by mithrendal** [comment]
> I found that touching a bit below the icon manages to trigger the action in landscape

when touch events on the very edges of the screen normally trigger the ios gestures for swiping down control center or how that thing is called... therefore these touch events are sometimes discarded by iOS I guess ... I saw that too ... solution would be to make the nav bar larger  which is also not so good as these devices like iPod touch are damn small

> I just got another problem with Gravity Force on my ipod, for a moment the joystick area was on the right side, overlapping the fire button, instead of the left side... 

this one seems to be a real bug ... open an issue when we want to see it to be removed ... we also could solve this by don't draw the circles at all ... what do you think ?
