### ISSUE TITLE
Fire power 

### ISSUE THREAD

**Issue by Vweber73** [vAmigaWeb/vAmigaWeb#75]
Fire power has shaky, flickering graphics and a bit blurry too, comparer to RetroArch/PUE...

**Comment by mithrendal** [comment]
Maybe it is driving an interlace resolution… try activate the gpu shader in the settings and restart vAmigaWeb. Only the shader handles interlace modes correctly. I did set the default to software renderer as some very old devices with old gpus having difficulties. Set it to gpu shader.

**Comment by Vweber73** [comment]
I did this.
No change, still shaky and flickering at times...

**Comment by mithrendal** [comment]
Can you make a picture so that I know where flickering happens when I try to reproduce… or just post me the snapshot.

**Comment by Vweber73** [comment]
Here we go.
Can't take a picture, it comes and goes, when you move and scroll...
[Firepower (1987)(MicroIllusions)_snap5.zip](https://github.com/vAmigaWeb/vAmigaWeb/files/8597521/Firepower.1987.MicroIllusions._snap5.zip)

**Comment by mithrendal** [comment]
yes I see it now ... it looks as if portions of the screen are updated while being displayed ... which you normaly see if game does not use double buffered drawing code... we have to check the vAmiga Mac version and compare it to WinUAE  ...

**Comment by Vweber73** [comment]
Thanks ! So vAmiga is not based on UAE ? I thought it was the case somehow...
Different emulators have different strengths... VAmiga seems able to run Code trash demo to some point... whereas it fails from scratch on RetroArch/PUE with an OCS/ECS configuration even with cycle exact emulation... only with AGA it works... Very strange !

**Comment by mithrendal** [comment]
vAmiga was developed from the scratch by @dirkwhoffmann . it has a very clean and modern code base 😎.... whereas all UAE decendants have a more or less historic code base 😬... 

it was started from zero in februar 2019 see https://github.com/dirkwhoffmann/vAmiga/issues/1

**Comment by Vweber73** [comment]
Excellent, thanks ! Always great to have alternatives ! I was wondering why Super Denise and AGA were not included, since I thought they were développed... They are not, ok :)

**Comment by dirkwhoffmann** [comment]
I tried the game in the Desktop version and it seems to work fine. 

<img width="1044" alt="Bildschirmfoto 2022-04-30 um 22 03 46" src="https://user-images.githubusercontent.com/12561945/166120971-983cbf85-7aa5-4767-8717-d30957b1eaa9.png">

It might be an issue with compatibility settings. Did you run the emulator with "high accuracy" settings? 

BTW, do I need to take down the choppers or are they on my team?

**Comment by Vweber73** [comment]
Is there such a thing as high accuracy settings in vAmigaweb ? Did'nt see that !
The choppers are ennemies, they will take you don't if you don't take them down first :)
This being said, the soldiers you free are on your side, but you can run over them and spill their blood. One of the guilty pleasures of this game. Those days were merciless and unethical ;)

**Comment by Vweber73** [comment]
There is still a bit of flickering, when the thank moves fast... Less than before but more than RetroArch...

**Comment by mithrendal** [comment]
we should investigate where this comes from

possible causes:
1. game just flickers somewhen
2. device 
3. vAmigaWeb emultator UI
4. vAmiga core

maybe we are  able to rule out some points above? have you checked other games ? Is it only this game ... does it exhibit this on other devices too (laptop)?

**Comment by Vweber73** [comment]
1-Possible that the games flickers in itself, this is a demanding game, but I see quite a few differences between emulators and machines, and i didn't see flicker in other games (Gravity Force has very very slights scrolling lags once in while, but that's it)
2-I did check on Ipad, and it seems it flickers way less than on my Android Z3 !?
3-I couldn't try vAmiga on Mac, don't own a Mac...

**Comment by mithrendal** [comment]
![1FBCCC55-3E36-4D66-9D83-43F8BAB28D41](https://user-images.githubusercontent.com/17108995/167243134-300a3677-4599-40a5-89da-e4b7e11ed6ce.jpeg)


Start it and let it run 15 seconds or so and after that enable live debug and check framerates . Like in the pic above. (Livedebug itself puts stress on slower devices so be sure to enable it at the very end… not in the beginning)

**Comment by Vweber73** [comment]
I did so.
The "executed" is pretty much constant, around 50, sometimes a bit more (51-52).
The "rendered" is always way above, from 57 to 100, depending on what's going on on screen. I saw it flickering while "executed" was at 80.

The Z3 is not exactly a slow phone, that's one of the most powerful phone on the market :) if it can't do it, not sure what device can !

Cheers

**Comment by mithrendal** [comment]
> I saw it flickering while "executed" was at 80.

really ... that would explain the flickering ... as it is executing too fast ... amiga frame execution should always be at 50 because of PAL 50Hz... if thats true it somehow executes too fast and therefore maybe these flickering ? Could you verify that it is really executed which showed 80 and not rendered ?  Maybe try to turn warp off ... could be that the game loads from disk and hence time warps (i.e. executes forward faster than it renders) ?

**Comment by Vweber73** [comment]
Sorry, my bad. I meant "rendered", not "executed", was never was above 52 !

**Comment by Vweber73** [comment]
Turning off warp mode doesn't change anything to the flickering... Anyway there are not disk loads during playing.

**Comment by mithrendal** [comment]
we have to find out whether it is emulation related or not. If emulation related then it has to be solved in the vAmigaCoreLib by @dirkwhoffmann if not then me.

lets test some similar scrollers ... speedball2 or xenon 2 mega blast for example.  could you give them a try to see similar flickering... if you see flicker too then certainly not emulation related but me ...  if you don't see flicker then possibly @dirkwhoffmann

**Comment by Vweber73** [comment]
I tried both. No flicker whatsoever !

**Comment by mithrendal** [comment]
Ok. 🤔 

can you describe the flicker? Could you record a screen movie? And post here? Has to be less than 10mb so must be very short

**Comment by Vweber73** [comment]
Here we go, I tried to make it short with no sound, not sure it shows the problem well...
https://user-images.githubusercontent.com/92450215/167254908-69ea6849-15ee-499b-9a27-8f197ea56ab0.mp4

**Comment by mithrendal** [comment]
yes I saw it ... in the upper left corner right ?

**Comment by Vweber73** [comment]
Yes, among others. This does not happen in Retroarch

**Comment by mithrendal** [comment]
I am going to double check the double buffering as it seems to draw only into active screenbuffer (i.e. the buffer currently visible) ... that is at least what it looks like ... stay tuned ...

**Comment by Vweber73** [comment]
Thanks !
I wonder also if there are not timing issues... Burning Spear demo (the one that shows the ECS Agnus émulation bug) takes time to transition from one sequence to another, there is a noticeable break, at least in sound, every time...

**Comment by mithrendal** [comment]
I think we might have some sync issues in vAmigaWeb... can you change screen refersh rate on android Z3 Fold? from 100hz to 60hz ? or 50hz? maybe I already spotted the problem in vAmigaWeb source code ... but I am not sure yet ... we have to try ... If you could change the refresh rate of your device and when this also changes the flickering then this would be a strong evidence that something is going parallel which I thought it would not be the case and then we would know how to handle this ...

**Comment by Vweber73** [comment]
Ouch, sounds like heavy stuff to do on my phone - RetroArch does not ask any phone adjustment ! :)
I have done a quick research, I found that i have 2 "motion smoothness" settings, the current one is "adaptative", up to 120Hz, the second one is "standard", 60hz. Is this what you want ? Do you want me to switch to standard and try again Burning Spear and Fire Power ?

**Comment by mithrendal** [comment]
yes go to 60hz and see whether it changes the flickerbug ... when this is the case then I know where too look for the bug in vAmigaWeb ... and later it should run as smooth as the RetroArch thing (which I can not install since I am on iOS)

**Comment by Vweber73** [comment]
I have done so.
-Fire Power flickers much more !
-No obvious change in Burning Spear, each sequence still works fine, each transition is a bit choppy in sound.
Btw the first intro screen seems to be in interlaced resolution, il flickers a bit, but it does not flicker in RetroArch which has a built-in flicker fixer. Is it the case with vAmigaWeb ?

**Comment by mithrendal** [comment]
Use gpu shader has build in flicker fixer

**Comment by Vweber73** [comment]
Yes, thanks. It works better in the beginning with this render, but then it flickers again a bit... This burning Spear demo is a good case study, it keeps changing resolution, requires cycle-exact, makes use of very rare features like ECS sprite range increase, as seen in the bug... If this one works, everthing will ! :)

Cheers

**Comment by mithrendal** [comment]
fire power ... I just found a bit of time for research... 

in order to constantly being able to reproduce the problem I found something strange ...

when launching firepower with kickstart 3.1 game exhibits in all tries the flicker problem

when launching firepower with kickstart 1.3 game has no flicker problem

could you see that too on your side ? the snapshot you sent me was booted with kick3.1 ... first I only could reproduce the flicker from this snapshot ... then I wanted to reproduce but could not with kick1.3 so ... maybe in the end ... might be only a kickstart compatibility issue ???

**Comment by Vweber73** [comment]
You're right !! Way less flicker on 1.3 than 3.0 ! Almost not at all, matching the real thing I think :) still, you corrected something in the code a few days ago, right ?

Seem to be impossible to change the kickstart while in a snapshot - you have to restart the app, normal ?

Cheers

**Comment by mithrendal** [comment]
according to https://github.com/vAmigaWeb/vAmigaWeb.github.io last update was two days ago 😇 only updated the reset bug when dragging in a zip file and the virtual keyboard option nothing else...

>Seem to be impossible to change the kickstart while in a snapshot - you have to restart the app, normal ?

when in a snapshot and when you choose another kickstart it should normally insert the kickstart roms and do afterwards automatically an amiga reset and boot the floppy disk again... no need to restart the complete PWA... (and yes no hot swapping kickstart while in a game session possible)

**Comment by Vweber73** [comment]
Strange, my request to change the kickstart from 3.1 to 1.3 was purely ignored. Trying to change for 1.2 worked on the contrary, the Amiga resetter ! De

**Comment by dirkwhoffmann** [comment]
> Strange, my request to change the kickstart from 3.1 to 1.3 was purely ignored

There are multiple version of this Kickstart. You need to use the one which is named something like this:
Kickstart v3.1 rev 40.63 (1993)(Commodore)(A500-A600-A2000).rom or 
Kickstart v3.1 rev 40.63 (1993)(Commodore)(A500-A600-A2000)[!].rom

**Comment by Vweber73** [comment]
Thanks ! But what I mean is that it generally works. I could always switch to it, just not in that particular situation (in a middle of a snapshot)...

**Comment by mithrendal** [comment]
@dirkwhoffmann I think @Vweber73 is speaks about hot swapping the kickstart while in a game session ... that is not possible because @dirkwhoffmann vAmigaCoreLib requires a shutdown of the emulated Amiga when swapping kickstart roms ... 

@Vweber73 how did you try to swap ? there are two ways to do it ... I would like to reproduce ...

**Comment by Vweber73** [comment]
I simply went to the seeings, kickstart, touched the box to select the already available ones (not the file selector to import a new one).Touching 1.2 worked fine and resetted the Amiga, touching 1.3 was ignored (3.1 was kept and the snapshot kept going).
Once the Amiga resetted, switching to 1.3 worked fine again...
Cheers

**Comment by mithrendal** [comment]
maybe you had the emulator at pause ?

I just tried and it always resetted but when I halted the emulator and then was switching between kickstarts then no reset seemed to be happen ... until I pressed pause again and made it running ... then the reset took place

regarding the flicker in fire power with kickstart 3.1 can someone try that in WinUAE ? Is the retroarch PUAE running 3.1 too? with 2MB Chip and ECS Agnus?

**Comment by Vweber73** [comment]
No, I didn't pause it... Very strange.
I confirm that in RetroArch, with A600 preset (3.1, 2Mb Chip, 8Mb Fast), there is a lot of flickering, so this seems indeed related to the kickstart ! Thanks and sorry for wasting your time with this.
On the other hand, the Burning Spear in vAmigaWeb demo has jumps between sequences, and not in RetroArch, regardless of the kickstart. It seems that this is every time their is a change of resolution (which happens a lot in the demo that seems to push the Amiga to its limits).

**Comment by mithrendal** [comment]
>No, I didn't pause it... Very strange.

is this reproducable ?

>I confirm that in RetroArch, with A600 preset (3.1, 2Mb Chip, 8Mb Fast), there is a lot of flickering, so this seems indeed related to the kickstart ! Thanks and sorry for wasting your time with this.

you are welcome ... and thanks for testing and bringing this up to the table... this testing input is very valuable ... sometimes false positive ... that is normal ... on the other hand we have not really changed any line of code for it ...

>the Burning Spear in vAmigaWeb demo has

yes lets check this now...

**Comment by mithrendal** [comment]
>On the other hand, the Burning Spear in vAmigaWeb demo has jumps between sequences, and not in RetroArch, regardless of the kickstart. It seems that this is every time their is a change of resolution ...

I have watched it on a powerful laptop ... no jumps at all ... do you see frame drops when it switches between the sequences ? Just the defective sprite and some gfx corruption when using display area=standard  ... wide did not have any ... my flicker fixer requires the display area height to be even ... might be that it is uneven when size = standard ... I will check

**Comment by Vweber73** [comment]
Not really frame drops. Rather a small pause... Sounds interrupts then resume...but still in synch with the picture...as if changing the resolution took time and introduced delay. Strange...
Yes the sprite corruption is the ECS Agnus émulation bug we already talked about, but that's something else...
Seems I have the "pause" in any screen mode, will check again

**Comment by Vweber73** [comment]
https://user-images.githubusercontent.com/92450215/167314371-699b5009-f25e-4dec-9b0b-1f42ed2867c7.mp4

Here is a short sequence at the beginning, with sound, shows the problem quite well

**Comment by mithrendal** [comment]
Oh now I know what is going on 😂 ... between these sequences there is disk drive activity and you have warp enabled ... so when disk drive is loading the warp fast forward kicks in ... and therefore it disables the sound ... otherwise there would be to many sound data to process ... also frames are skipped in warp

so just disable warp and then the sound drop will go away ;-)

disable warp ...

**Comment by Vweber73** [comment]
Oops... I'm so ashamed of myself... So sorry I made you waste your time... I suppressed warp and yes now it is working like a charm ! 

Only one thing for my defense, it is not easy to spot that you have disk activity when you have no sign of that... Neither visual (disk diode) nor audio (disk sounds). That's why I love the status bar in UAE, as well as the disk sounds, hope this can be implemented at some point ! :)

Thanks again and cheers

**Comment by mithrendal** [comment]
yes we should make an indicator for floppy disk / hard drive activity ... maybe in the file slot we just put in there the track numbers ... or an extra overlay ? don't know yet ... but that should be something we can use for vAmigaWeb and vc64web ...

also would be good to show when it is warping ... i.e. when the warp kicks in

we should do this in the next weeks or so... it is easy ... but first keyboard for vc64web I think...

**Comment by Vweber73** [comment]
Ok, excellent, thanks !
