### ISSUE TITLE
Agnus emulation 

### ISSUE THREAD

**Issue by Vweber73** [vAmigaWeb/vAmigaWeb#77]
Hi, 

Something funny regarding compatibility.

See this interesting post from Toni, Burning Spear demo is supposed to have a corrupt sprite in the middle of the screen only on OCS Amiga. But vAmigaWeb shows this corrupt sprite even when ECS Agnus is selected !

http://eab.abime.net/showthread.php?t=11295&page=2

Is sprite's vertical range increased as it should be (but not working) or is this a missing feature ?

Cheers

**Comment by dirkwhoffmann** [comment]
> or is this a missing feature ?

Yes, it's a bug. Thanks for reporting!

**Comment by Vweber73** [comment]
You're most welcome :)
Are the other Agnus differences mentionned in Tony's post properly handled ? It seems that it is the case: original éditions of Eliminator and Double Dragon II are famous for having screwed up graphics on ECS Agnus, and I tested this to be the case in vAmigaWeb (they work fine when OCS Agnus is selected).

**Comment by dirkwhoffmann** [comment]
> Are the other Agnus differences mentionned in Tony's post properly handled ? 

Some OCS / ECS differences are handled, but not all of them. E.g., I wasn't aware of the sprite difference until today. It might be best to test all titles mentioned in the EAB thread.

**Comment by Vweber73** [comment]
I tried to do this...

- Finer display dma start/end position (DDFSTRT/DDFSTOP bit 1 is used on ECS/AGA, ignored on OCS) Game examples: Eliminator and Double Dragon 2 (corrupted graphics on non-OCS Amigas)

=> Confirmed ok 

- VPOSR-register. Chip identification bits changed, some programs don't mask these out when comparing vpos and freeze on non-OCS Amigas or vice versa.
-
=> No example given, so no idea. Is this implemented ?

- Sprites' vertical start and end range increased. Example: Burning Spear -demo shows corrupt sprite on the middle of screen on OCS Amigas..

=> Bug confirmed - fix on the way ? :)

- Playing with bitplane DMA enable bit during display window works differently on OCS and ECS Amigas. Example: Accession intro (don't remember the name) has display corruption on non-OCS Amigas.

=> No sure of which Accession intro we talk about... Any idea ?

- Reading non-existing custom registers works differently on OCS and ECS Amigas. Example: Codetrash-demo only works on OCS Amigas.

=> I tried the Codetrash demo and came to no definite conclusion. It is very long, so it is painful to let it go until a possible failure...it behaved strangely when switching from ECS to OCS, I has to reboot several times for it not to freeze from scratch (why so ?).  In vAmigaWeb it seems that both OCS and ECS configs fail after a long while (you have to go after the slow Mandelbroots, then wait a lot after the RGB Plasma being done over and over, then you have a fix grey screen, I don't think it is supposed to be like that). I tried PUAE in RetroArch using the Fast Forward feature (by the way I would love this feature in vAmigaWeb !), but it didnt go very well, it seems the FF feature fails in the plasmas, doing them over and over...
Any idea about the behavior of these custom registers ?

**Comment by Vweber73** [comment]
Hi,
Any progress on this front ? :)

Thanks and cheers

**Comment by mithrendal** [comment]
for the PWA versions I am just waiting for his changes to the emulation core and then I will merge them over into here....

dirk is currently on refactoring code in virtualC64 ... when he is done with that he will certainly start investigating  into it

follow your issue in the emulation core project https://github.com/dirkwhoffmann/vAmiga/issues/692

**Comment by mithrendal** [comment]
![image](https://user-images.githubusercontent.com/17108995/169338054-8a2c10da-ad27-4c4c-8b6d-5daf0ad0b3e4.png)

merged todays vAmigaCore into vAmigaWeb ... did not yet published it to the net ... stay tuned ... first some obligatory checks ... and last but not least ... lets activate overclocking in this new vAmigaCore 😎

**Comment by Vweber73** [comment]
Wow, excellent ! Overlooking is all what is needed, as far as I know no OCS/ECS game or app requires more than 68000 instructions... Maybe when AGA is emulated, the 68020+ will need to be emulated as well :)
I stay tuned, can't wait, thanks !
Cheers

**Comment by mithrendal** [comment]
![image](https://user-images.githubusercontent.com/17108995/169400671-dbfbb4f3-94e8-4f45-b692-3a576e6d832d.png)

and out 😎
