### ISSUE TITLE
Snapshot Browser failing after too many snapshots

### ISSUE THREAD

**Issue by RobFullwood** [vAmigaWeb/vAmigaWeb#82]
Hi team, not sure if this is the right place, or if this is a known issue...

History:  I am an Amiga user from way back (still own an Amiga 1000!), and discovered this project a few weeks ago - IT'S AWESOME!  I just want to play with an Amiga on my iPhone 13 and iPad Pro - so far so good.

I have already played a LOT of Populous 2 on my iPhone (many hours in fact!), and it works surprisingly well.

However, after i have stored a lot of snapshots, the next time i open the snapshot browser, i get an error:

Value NaN is outside the range [-2147483648, 2147483647] (I am not sure if the numbers change).

Once this happens, the snapshot browser is useless, and i can't access my snapshots.  I have to create a new Home Screen icon from Safari, and start afresh.

Not so much of a problem for Populous 2, because that one shows character codes, and level codes, which i just screenshot when i complete a level.  Just a bit of a pain on this one.

However, i just tried starting with Ultima III on my iPad Pro, and discovered the same error - this one's a show-stopper, because it doesn't seem to save the game to the ADF, so i am back to square one when I lose access to the snapshots.

So, i think i have identified 2 issues here:
- Too many snapshots seems to break the snapshot system, requiring a complete start from scratch.
- The emulator doesn't "save" progress to the game ADF.

Oh, and ONE more (should i have started a separate post?):
- Is there any possibility of using the touchpad on the Magic Keyboard on the iPad Pro as the Amigas mouse?  That would make this project perfect (well, for me anyway!).

Absolutely LOVING this emulator - for many years i have dreamed of having an Amiga on my phone, this is SO close to reality!

Keep up the amazing work people!

**Comment by mithrendal** [comment]
>  I am an Amiga user from way back (still own an Amiga 1000!) 

me too 😍

>However, after i have stored a lot of snapshots...

how many snapshots did you save ? approximately ... hm, I never did an upper boundary test on the amount of snapshots ... I probably should have test this ... so my question how many do I have to do to get this error ... 50, 100, or even more ?

(just to be sure ... I assume you did already know that you also can delete snapshots, no ?  There is a small white cross on the upper right of each snapshot picture ... you also could export them with the icon on the lower right to bring them to another device)


>The emulator doesn't "save" progress to the game ADF.

ups that should work, when you going to take a snapshot, then there is a green button saying export disk in df0 or something like that... maybe it is buggy ? I will test this too ...

>Is there any possibility of using the touchpad on the Magic Keyboard on the iPad Pro as the Amigas mouse?

the question is whether it supports the HTML5 pointerlock api... you could try this ... 

- put `mouse` into Amigas port1  (do not select `mouse touchpad` as this would be the touchscreen mouse emulation)
- boot up workbench and try to click and move  


>Absolutely LOVING this emulator

thank you ❤

>Keep up the amazing work

will do

**Comment by RobFullwood** [comment]
Wow, fast response!  

Number of snapshots - haven't counted, but around 50 or so - I will watch!

And yes, i know about deleting snapshots, now that i am seriously (seriously!) back into Populous 2, I always cull out the unused snapshots to avoid this issue.  I just forgot to do this with Ultima III, dammit!

I just tried again, and SOME of the snapshots DO work,  but the error message stays on screen, which makes it more or less unusable.

(By the way, same snapshot error on iPhone and iPad Pro)

Saving to the ADF - the Snapshot DOES indeed save the inserted disk, but i don't believe it "writes" to the ADF.  Ultima III (along with plenty of others i expect) uses the main game disk as the 'save disk'.  You create a party, then "Journey On".  I created some characters, played the game, saved progress throughout.  When the snapshot broke, i booted up the ADF fresh, and it was back to default - none of the saved characters, none of the progress.

Magic Keyboard/Touchpad - I tried setting it to "Mouse" (along with every other setting!) and it doesn't move the Amiga mouse, just floats the usual Apple iPad grey circle around the screen (which i can still use to select the emulator's menus, etc).  Not a deal breaker, just in the "nice to have" column!

Thanks again for being so active on this project :)

**Comment by RobFullwood** [comment]
Oh man, and i just realised what you mean by exporting the snapshots, and loading them up!  Game changer... ;). Unfortunately, when it breaks the snapshot browser, it breaks the ability to export any further snapshots.  Not explaining myself well, here's a pic! 

(the image shows the broken snapshots - there are many more to the right of the screenshot)
![IMG_0042](https://user-images.githubusercontent.com/105273792/167600276-1dbf5ed2-a7d3-4cdc-819b-8ef06c7b0553.jpeg)

**Comment by mithrendal** [comment]
>Saving to the ADF - the Snapshot DOES indeed save the inserted disk, but i don't believe it "writes" to the ADF. 

I just tried ... booting up workbench disk ... opening workbench preferences ... setting to interlace ... hit the save button in workbench preferences app...

vAmigaWeb->take snapshot-> hit the green button disk in drive 0

this exported the ADF to iPhone filesystem 

removed vAmigaWeb from iPhone memory completely restarted it (coldstart)

upon disk-hand screen put in the exported workbench disk and it booted up with the changes ...

so this should work ...

What could be the problem is... that you exported maybe the wrong disk ? Lets say Ultima has three disks ... one of them the save disk... then you have to hit the green export button when save disk is inside df0:

**Comment by RobFullwood** [comment]
Aha, saving the state of the disk via the green button works!  I didn't realise the functionality of that feature - awesome :)

Asm for the others:
1. I have kept the instance on my iPad with the broken snapshots
2. Yes, i can load the snapshots that display thumbnails - however, when it tap on them, the "loading, please wait" message stays onscreen.  Screenshot added.  But i can't load the 'broken' snapshots (the ones without thumbnails)
3. scrolling right - they are all broken - all the way to the right.
4. hmmmm, don't know the answer to this one unfortunately - I never went to load up the snapshots before.  I just kept on taking snapshots, then when i had to load a snapshot back up, that's when i noticed.  Sorry about that.

![IMG_0043](https://user-images.githubusercontent.com/105273792/167746606-77b28530-28f3-46cf-b9eb-b82f9d834aef.jpeg)

**Comment by mithrendal** [comment]
Thank you for testing...

The problem I think is that one broken snapshots stops the complete loading snapshot browser loading... 

I have put a try catch around the thumbnail drawing code ... so with a bit luck it will work now... one snapshot would be probably still bebroken but the others more to the right in case they were fine would still be there and the progresbar should go away too..

please be sure to hit settings->update installation

**Comment by RobFullwood** [comment]
You, my friend, are a certified genius!  That completely did the trick on my instance with broken snapshots - they ALL came back perfectly!

Pity the iPad mouse pointer doesn't seem to support the HTML5 "pointerlock" api...  A quick bit of googling seems to indicate that mobile browsers don't support this (yet!).  Maybe the next iOS and/or Safari update will give this to us!

And now that i know about exporting the snapshots, and saving the state more permanently, I have fully cloud-based, cross-platform save states!  Put THAT on the box!

As a kid in the 80s, i would never have even thought about carrying around a fully-functional Amiga in my pocket.

Thanks again Mithrendal!

**Comment by RobFullwood** [comment]
Ah yes, i am tending to use the save disk function more frequently now.  Having that available gives me the 'trust' i need to actually get into a long-play type of game.  Looking forward to v2!

**Comment by mithrendal** [comment]
V2.0 released 😎.  Hope it will work well for you if not then just report…

**Comment by mithrendal** [comment]
>Pity the iPad mouse pointer doesn't seem to support the HTML5 "pointerlock" api... A quick bit of googling seems to indicate that mobile browsers don't support this (yet!). Maybe the next iOS and/or Safari update will give this to us!

Hi @RobFullwood I have found an alternative way to get relative mouse coordinates without pointerlock… can you try the current version with your iPadPros mouse pad ? I have it here working on iPad with a Magic Mouse gen1 …😎 on current vAmigaWeb version `ui 2023_03_11`

You have just to select `mouse` … on iPad it will then detect that there is no pointerlock API available and therefore it will activate my hacky fallback implementation… which works quite satisfying for me

**Comment by RobFullwood** [comment]
Well holy heck, you have done it again!

Yes, I can confirm that this works with my iPad Pro’s Magic Keyboard and touchpad.  Amazing!

It’s obviously a little strange (the little circle that follows the built-in touchpad doesn’t match where the Amiga pointer is, but once you start ignoring the apple ‘pointer’ - and realise “everything is relative” - it works great!

Even to the point of single finger click is left mouse button, and double-finger click is right mouse button!

This might be enough to get me back into playing with the Amiga on my iPad…

Thanks again for the amazing work!!!!!!!

😃



Best regards,

Rob Fullwood
Director  |  IQPC
***@***.***
1300 662 779  |  ***@***.***>  |  Web<http://www.iqpc.net.au/>  |  ***@***.***,115.8094783,17z/data=!3m1!4b1!4m5!3m4!1s0x2a32afa95dd5d6ef:0xd707384c7aa5d5d4!8m2!3d-31.8871772!4d115.8094783>


From: mithrendal ***@***.***>
Date: Sunday, 12 March 2023 at 5:50 am
To: vAmigaWeb/vAmigaWeb ***@***.***>
Cc: Rob Fullwood ***@***.***>, Mention ***@***.***>
Subject: Re: [vAmigaWeb/vAmigaWeb] Snapshot Browser failing after too many snapshots (Issue #82)

Pity the iPad mouse pointer doesn't seem to support the HTML5 "pointerlock" api... A quick bit of googling seems to indicate that mobile browsers don't support this (yet!). Maybe the next iOS and/or Safari update will give this to us!

Hi @RobFullwood<https://aus01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FRobFullwood&data=05%7C01%7Crfullwood%40iqpc.net.au%7C613c8e3de43d4c03766308db227a98a8%7Cffe37063ec77434a9eea52ead892469c%7C0%7C0%7C638141682175353503%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C7000%7C%7C%7C&sdata=BnOhFEsE9UgXwBiv%2BFIOAs9sFrn3AjUAuO7bVHESSag%3D&reserved=0> I have found an alternative way to get relative mouse coordinates without pointerlock… can you try the current version with your iPadPros mouse pad ? I have it here working on iPad with a Magic Mouse gen1 …😎 on current vAmigaWeb version ui 2023_03_11

You have just to select mouse … on iPad it will then detect that there is no pointerlock API available and therefore it will activate my hacky fallback implementation… which works quite satisfying for me
