### ISSUE TITLE
Sound volume

### ISSUE THREAD

**Issue by Vweber73** [vAmigaWeb/vAmigaWeb#91]
The volume is pretty low compared to PUE for instance... Let's pump it up ! :)

**Comment by Vweber73** [comment]
Aside from volume, I now hears small cuts regularly in Settlers intro music, which I don't think I heard previously. Maybe linked to the PAL/NTSC switch issue ?

**Comment by mithrendal** [comment]
I doubled the sound volumne ...
merged in latest v2.1Beta2 Core


can you test ? can we push it to the regular version? can you check?

**Comment by Vweber73** [comment]
Thanks !
I tested.
Things seem to be fine. The sound level is definitely better.
I now have disk polls. 
The only thing is - the drive noise is very strange. Does not sound like a disk...

**Comment by Vweber73** [comment]
Thanks ! I switched to the regular URL :)
Any idea to improve the drive clicks sound ? And to make this drive sounds optional ?
One very small item: the track indicator has no fixed width i.e. you can have dh0:2 and dh0:43, not very aesthetic...
Cheers
