### ISSUE TITLE
Status bar and floppy sound 

### ISSUE THREAD

**Issue by Vweber73** [vAmigaWeb/vAmigaWeb#92]
A status bar showing disk(s) activity with track number and sound, like in UAE, would be quite useful to know what's going on...

**Comment by mithrendal** [comment]
track display for floppy and harddisk ... done 😎
drive step /eject / insert sounds for floppy and harddisk ... done 😎


pushed to uat https://vamigaweb.github.io/uat/

**Comment by mithrendal** [comment]
yes true .. but I am still fighting iOS to unlock the audio .... it does not allow to play at the moment ... does it play on android ? ... on desktop it plays fine

**Comment by Vweber73** [comment]
On Android I get floppy sounds (quite loud) and game sounds (not as loud as I would like, but same as before).

**Comment by mithrendal** [comment]
yes we should make game sound louder ... or user adjustable ... and the drive sound with lower volume


still fighting with iOS

**Comment by Vweber73** [comment]
Yes, one may want to turn disk sounds completely off...

**Comment by Vweber73** [comment]
I noticed that now the app tends to restart frequently, once you come back after you suspended it. Before you could leave it for long, and get to your previous content. Has anything been done in that direction ?

**Comment by Vweber73** [comment]
I have no floppy sound nor disk track indicator anymore ! Did you roll back the changes ?

**Comment by mithrendal** [comment]
Restarts I think are die to the fact that I pushed so often a new Version maybe? I did 6 times or so. 

Still fighting iOS. Better you stop testing until iOS Audio works … I will tell you

**Comment by Vweber73** [comment]
Ok ! Can you just confirmed that the floppy sound / track display is not there anymore, it's not a problem on my side ?
Cheers

**Comment by mithrendal** [comment]
It is still in it but I tried several things to make it work in iOS… so maybe I broke something. On desktop it still visible… try a desktop browser

**Comment by Vweber73** [comment]
When I try the UAT URL on a browser, I get this error many times prior to launch, and even after launch. It is the new version.
When I try the shortcut on my Android phone, which used to point to the new version, but now, without me doing anything, seems to point to the old version. As it it fall back because of the error ?
![Screenshot_20220609-101257_Chrome](https://user-images.githubusercontent.com/92450215/172799684-c5da95ce-e820-49d7-a24d-4f622952aa6f.jpg)

**Comment by Vweber73** [comment]
I've just tried, and no change. The browser still goes to the new version with errors, and Android still goes to the old version with no errors...

**Comment by mithrendal** [comment]
ok fixed all those exceptions ... pushed it ... should work for you now ... iOS now still complains that it has no codec for .ogg audio ... I change the format to .aiff later today ...

**Comment by Vweber73** [comment]
Ok, thanks, working now.

At first I still had the old version, what I did is de-installing it and re-installing it, in pure Microsoft tradition. Now i have the new version, and it is actually called "UATvAmigaweb". I guess there was some confusion between the 2 versions earlier on, somehow the new URL was overriden by the old one...

It seems that the floppy sound is not there when there is no disc in the drive... What UAE does is to give you the "empty drive testing for a disk" sound :)

Cheers

**Comment by mithrendal** [comment]
Oh no ... chrome does not understand .aiff audio format but .ogg and safari vice versa ...

hm we must convert to .wav or .mp3 ... can you convert those audios ? do you have a tool for that ?

I attach the sounds here 

[Archiv.zip](https://github.com/vAmigaWeb/vAmigaWeb/files/8871977/Archiv.zip)

**Comment by mithrendal** [comment]
ok ... iTunes does the job ... no extra tool needed

**Comment by mithrendal** [comment]
pushed mp3 sound files... the drive step sound is horrible ... I try to lower the volumne and turn the paula volumne up a bit

**Comment by mithrendal** [comment]
> Is it planned ?

Error: I did not handle DRIVE_POLL ... fixed it and pushed to uat

**Comment by mithrendal** [comment]
changed the play back of audio sound when drive head steps ... now only three step sounds will be played in parallel ... which makes it more comfortable to listen to I think ... and it still sounds like a real drive...  pushed the optimized sound to the regular address you can compare it with the uat ... 

also I fixed the width of track number display

**Comment by Vweber73** [comment]
Thanks ! 

It is a bit better but still feels a bit strange. I think it is lacking a motor spinning sound or something...

The sound of Interceptor is perfect, the one of Settlers that has some small glitches here and there...

I had a strange bug that i have sometimes but not very often: when I reset and load a disk, at first the virtual mouse is not effective, no matter which port it is inserted, and actually you can insert it in both ports, whereas in normal operation only one is allowed... After playing with it for a while the mouse pointer finally reacts, but it takes a while...

Maybe you'll end up with a real status bars, with all drives tracks numbers and colors ? :) In that case it would be cool to have the actual screen resolution indicated, just like UAE :)

Cheers

**Comment by mithrendal** [comment]
>I had a strange bug that i have sometimes but not very often: when I reset and load a disk, at first the virtual mouse is not effective, no matter which port it is inserted, and actually you can insert it in both ports, whereas in normal operation only one is allowed... After playing with it for a while the mouse pointer finally reacts, but it takes a while...

because this is a not so easy reproducable ... I tried to upgrade the underlaying frameworks to latest versions which include many bugfixes ... i.e. jquery3.5 -> 3.6  and bootstrap 4.5.2 -> 4.6.1

pushed it to uat

**Comment by Vweber73** [comment]
Ok thanks ! Did you manage to reproduce it, or not ?

**Comment by mithrendal** [comment]
no ... but one time I had something strange too... I was selecting the port and then the selectionbox did go into background i.e. behind the emulation canvas (it was still slightly shining through it) and I could not recover else then to restart the app completely ... that was on iPhone ... this led me then to the conclusion that something with the framework might be buggy ... according to the logs they fixed focus problems and other bugs ...

lets do now the following  ... when the version with upgraded frameworks works well then we take it and then we closely observe whether the problem shows up again ...

**Comment by Vweber73** [comment]
Ok ! So far the new UAT version works well, the problem did not occur.

**Comment by Vweber73** [comment]
Hi,
I got the problem again even on the UAT version... the mouse is correctly set up. Resetting Inteceptor makes that the mouse has no effet, only if you go and re-select the mouse, then the mouse works....
Cheers

**Comment by mithrendal** [comment]
resetting interceptor ... do you mean you have a running interceptor and then you press the reset icon in the top navbar of vAmigaWeb?

**Comment by Vweber73** [comment]
That's it. Rebooting the disk makes the mouse unavailable, until you go into the mouse settings again.

**Comment by Vweber73** [comment]
Mouse touchpad. I know that mouse is not for that :)

**Comment by mithrendal** [comment]
I tried on iPhone and desktop chrome. But I cannot reproduce. Did you do something else? Does it always break the mouse when you reset?

**Comment by Vweber73** [comment]
It's only once in a while, most of the time it does not happen, I don't know which conditions trigger the problem...

**Comment by mithrendal** [comment]
was the keyboard open when it happened ?

**Comment by Vweber73** [comment]
I'm not 100% sure, but I think it was not

**Comment by mithrendal** [comment]
did not have success in reproducing it ... I tried everything to break it ...

hm maybe the bug only shows up on android? 

lets add some logging capabilities 

add an action button with following javascript

```
var script = document.createElement("script");
script.type = "text/javascript";
script.onload = () => {eruda.init();};
script.src = "https://cdn.jsdelivr.net/npm/eruda";
document.getElementsByTagName("head")[0].appendChild(script);
```

when hitting the action button it adds another button for the eruda logging console ... 

![image](https://user-images.githubusercontent.com/17108995/173449797-f2df1646-8b4a-42ed-87aa-b6a175407749.png)

when you hit the eruda button it gives you access to the logging console ...

when the error happens again you can look into it and report the error  here ...

I might include this super cool logging console in the next update ... what do you think ... it is better then my simplistic "live debug"

**Comment by mithrendal** [comment]
I replaced the debug console with the one of eruda ... moved the setting from first position to last position in the setting dialog

also upgraded to todays latest version of the core

pushed it to uat

snapshots are not compatible with older ones

now you can load the eruda console and when the error with the mouse happens again then you can open the console and go to errors and please make me a screen shot of it ... then I can fix it ...

**Comment by Vweber73** [comment]
Many thanks ! I upgraded, so far so good, no bug.
What are the changes to the new core ?
Cheers

**Comment by mithrendal** [comment]
The changes are https://github.com/dirkwhoffmann/vAmiga/issues/710

effectively the previous core had a bug and did cut the last line on some games

you can still see it in the rink a dink demo


![20A69F9E-0985-49E4-989D-BAF2F677F695](https://user-images.githubusercontent.com/17108995/173694863-6f455569-40c0-4b01-8d3e-e439ddc2bc2a.jpeg)

**Comment by Vweber73** [comment]
Thanks ! Cheers

**Comment by mithrendal** [comment]
I hope we can catch now more errors with the new log console. We will see what this new thing can do for us…

**Comment by Vweber73** [comment]
So far no error, and rink a dink runs fine :)
Just have the impression that the volume is back to weak?

**Comment by mithrendal** [comment]
Oh yes the volumne is back to weak.  Confirmed. Will correct it soon

**Comment by Vweber73** [comment]
Many thanks! Sound is back to louder :)
Yes the console is working fine. So far the bug has not reappeared...
Only thing is that the app restarts quite often after being suspended - giving the impression not really being an offline app, as discussed...
Cheers
