### ISSUE TITLE
GPU shader render precision 

### ISSUE THREAD

**Issue by mithrendal** [vAmigaWeb/vAmigaWeb#93]
The rendered output shows scaling precision issues which aren’t there when using software rendering…

the following picture shows the problem 

![Screenshot_20220524-001356_Chrome](https://user-images.githubusercontent.com/92450215/169913725-c5ee5c07-be35-4b2a-9fd2-3e6428bb20f5.jpg)

**Comment by Vweber73** [comment]
Great findings ! But although I am proficient in C/C++/Java programming, I lack the video knowledge to help...

**Comment by mithrendal** [comment]
I am also not an gpu shader expert only understand the very basics… 😬but I am sure we will solve this, no?

**Comment by Vweber73** [comment]
I'm sure you will ! You're the man ! :)

**Comment by mithrendal** [comment]
some articles for reference which are describing our problem 

https://colececil.io/blog/2017/scaling-pixel-art-without-destroying-it/
https://jorenjoestar.github.io/post/pixel_art_filtering/

**Comment by mithrendal** [comment]
more findings
when I use GL_LINEAR filtering then pixels are correct size for all display sizes but it gets blurry

![image](https://user-images.githubusercontent.com/17108995/170368262-86858087-9f51-46c0-b5f9-b428f64c70bb.png)

maybe still better then current situation ?

**Comment by Vweber73** [comment]
Well... The ultimate goal is the real thing ! :)

**Comment by Vweber73** [comment]
Congrats !!
Btw, restoring a snapshot does not restore anything in the parameters - not only the clock, but not the memory settings. Makes it a bit confusing...
Cheers

**Comment by mithrendal** [comment]
yes I know ... do you think we should reset the parameters in the settings dialog according to the loaded snapshot ? but then the loaded settings from the snapshot should not be persisted as default values, which are loaded on next cold start of vAmigaWeb right ?

**Comment by mithrendal** [comment]
could you make a new issue and describe the concept of how it should be to be less confusing ?

we close this now ok ? If something shows up we just reopen ...

**Comment by Vweber73** [comment]
Yes, just make them the parameters as long as the snapshot leaves, for consistency...
Cheers

**Comment by Vweber73** [comment]
Just one little thing with screen sizes: if you select narrow and bring the virtual keyboard, the top of the screen is a bit cut, unless you remove the menu bar with the button meant for it...

**Comment by Vweber73** [comment]
Yes let's close this one.
