### ISSUE TITLE
Offline install issue 

### ISSUE THREAD

**Issue by mithrendal** [vAmigaWeb/vAmigaWeb#94]
On my iOS devices the pwa can be started when offline. 😎

But @Vweber73 on a fold Z3 android device it seems not to work …🙈

see here

![Screenshot_20220525-000728_Chrome](https://user-images.githubusercontent.com/92450215/170140424-ad60ffce-e3e3-4824-86ed-e3202f85c5bf.jpg)

**Comment by mithrendal** [comment]
@Vweber73 

1. could you test vc64web.github.io whether you see the issue there too ?
2. could you test vAmigaWeb.github.io on your iPodTouch or iPad ? 

can you post the message which pops up ?

**Comment by Vweber73** [comment]
Hi,
1. On my Z3 In flight mode no problem to start vc64, even after closing all app's, but...the same thing with vAmigaWeb ! It seems that the failure on startup is not systematic, that sometimes everything is cached ok.
2. On my ipod touch in flight mode, first startup of vAmigaWeb is ok. Closing the app and restart gave the error attached.
Cheers 
![Capture d’écran   2022-05-25 à 12 59 33](https://user-images.githubusercontent.com/92450215/170248235-1109d203-1c36-4eb1-8b2b-e29527e36200.png)

**Comment by mithrendal** [comment]
>2.On my ipod touch in flight mode, first startup of vAmigaWeb is ok. Closing the app and restart gave the error attached.

do you remember when did your turn WLAN off ? Was it after the first startup?

**Comment by mithrendal** [comment]
Why I am asking this is because it might be that vAmigaWeb has a wrong implementation of the service workers lifecycle...

there is a lifycycle which is describe here https://flaviocopes.com/service-workers/#activation

it explicitely says 

```
The Install stage
If the browser determines that a service worker is outdated or has never been registered before, it will proceed to install it.

self.addEventListener('install', (event) => {
  //...
});
This is a good event to prepare the Service Worker to be used, by initializing a cache, and cache the App Shell and static assets using the Cache API.
```

what does our service worker ? 

https://github.com/vAmigaWeb/vAmigaWeb/blob/1024a74883e74a7c818e6ebff50106ec678d1aa7/sw.js#L4-L7

correct nothing... it does not fill the cache ... 


then after install of the new service worker i.e. after the app has been closed or reloaded activation stage begins ...

```
The activation stage is the third step, once the service worker has been successfully registered and installed.
...
It cannot interact with pages already loaded, which means the service worker is only useful on the second time the user interacts with the app, or reloads one of the pages already open.

A good use case for this event is to cleanup old caches and things associated with the old version but unused in the new version of the service worker.
```

now see look at what we do in activation 🙄
https://github.com/vAmigaWeb/vAmigaWeb/blob/1024a74883e74a7c818e6ebff50106ec678d1aa7/sw.js#L9-L20

we delete the old existing version and have nothing in cache after this event .... we rely that the following fetch events will fill the new version into the cache automatically

under which circumstances is vAmigaWeb not offline capable ?

1. you start vAmigaWeb -> there is a new version on the server 
2. it detects this and fires the install event -> we do nothing
3. you close the app
4. turn on flight mode / offline 
5. start the app -> new service worker activates -> deletes caches
6. wants to load new version from server -> booom!

**Comment by Vweber73** [comment]
I don't remember if I started vAmigaWeb a first time before switching off WLAN... maybe...
I tried again: I closed the app (which was on the error page I sent), switched WLAN off (it was on again), and started vAmigaWeb again: same error...
I switched WLAN off, came back to the app, booted fine. I closed the app, switched WLAN off, started vAmigaWeb, this time it booted fine.

Does it help ?

**Comment by Vweber73** [comment]
Yes, sorry i meant "ON".
Great news ! same on my Z3 ? New version out ? 
Cheers

**Comment by mithrendal** [comment]
Yes it is platform independent. I screwed up the PWA livecycle … when I correctly implement it then it should be ok

**Comment by Vweber73** [comment]
Got it, thanks !

**Comment by mithrendal** [comment]
for reference a `how to` guide for implementing updates which are controlled by the user instead of automatic 

https://whatwebcando.today/articles/handling-service-worker-updates/

**Comment by Vweber73** [comment]
Interesting, thanks !

**Comment by mithrendal** [comment]
That is a receipt for me how I have to change the installation process…

**Comment by mithrendal** [comment]
Hi just wanted to report that I am on my journey of making the "offline" installation process more transparent to the user. 


Here are two screen shots which did ... 

first when a new version is available it will report this with a toaster message to the user and let him decide whether to install or skip ...

![image](https://user-images.githubusercontent.com/17108995/177047684-0ff667e9-530c-4afc-aa0d-a3e122512550.png)


the second screen shot shows that in the settings dialog there is now information about what is currently installed

![image](https://user-images.githubusercontent.com/17108995/177047597-59e15ce6-ec27-4646-bfea-06c0cefa7b5f.png)


I also like to try whether it is maybe possible to switch between several installed versions ... this way also older snapshots are still playable...

**Comment by Vweber73** [comment]
Hi,
Excellent, many thanks!
It seems there is no new version online yet?
Cheers

**Comment by mithrendal** [comment]
no ... I don't dare to push it to uat.... It is still so alpha... 

should I dare it?

**Comment by Vweber73** [comment]
When you feel it's ready! :)

**Comment by mithrendal** [comment]
development version on my mac does not delete older installations anymore and can therefore activate different versions of vAmigaWeb ... solving thereby the "broken snapshot on upgrade to new version" problem ...

![image](https://user-images.githubusercontent.com/17108995/177217263-22dab9b3-ce66-47c6-a380-2835d67fa631.png)


see here three different versions are installed ...

![image](https://user-images.githubusercontent.com/17108995/177217588-dfd562c9-eaff-4713-9fd0-97235976adc2.png)


the list of installed versions would become over time to big, no? 🙄

how to design the deletion of older versions 🤔? hmm.... lets think about it tomorrow 😴

**Comment by Vweber73** [comment]
I personnally don't require several versions installed at one time :) but if the feature is there, why not, thanks!
Cheers

**Comment by mithrendal** [comment]
![image](https://user-images.githubusercontent.com/17108995/177418212-ebafce62-72a8-42da-8531-8153e3023f0f.png)


I will put it to uat now....

when you got an older version without installation management then it will enforce the upgrade as usual ... once you are on the newer version ... everything will be completely transparent ... and off line mode should work reliably ...

**Comment by Vweber73** [comment]
Excellent, thanks!
First time I tried I got this... But I relaunched and it was OK. Only a one off problem? 
![Screenshot_20220705-232935_Chrome](https://user-images.githubusercontent.com/92450215/177419845-7bb11164-2957-480e-a4d7-7cb57b708ccf.jpg)

**Comment by mithrendal** [comment]
yes me too ... just pushed a bugfix

**Comment by Vweber73** [comment]
Great!

**Comment by mithrendal** [comment]
I did reatart the app a few times without clicking “update installation” and it gives me this

![F6C5FBC8-F9FA-4FC5-B1AE-DA0F095FC425](https://user-images.githubusercontent.com/17108995/177423375-c53aeb60-7bfe-4c36-849c-fe1a3d6bcb26.png)


Looks as it does work on iOS 😎

**Comment by Vweber73** [comment]
Works well on my side! And doesn't even break my snapshots :)

**Comment by mithrendal** [comment]
No because the core is still the same 😂

now we can upgrade to beta3 soon without fear. Because we can always go back in history 😎

In the coming days.

**Comment by Vweber73** [comment]
Fantastic job! Thanks and cheers

**Comment by Vweber73** [comment]
Hi,
Today the uat version was back to prior the versions management feature. I upgraded and this version was restored, but without letting me install previous versions as before. The version is dated yesterday, has anything changed?
Cheers

**Comment by mithrendal** [comment]
Yes. I did will do change the versions without and with version management a couple of times. In order to test a smooth migration for the regular version in mind.

**Comment by mithrendal** [comment]
![998C1CD5-D184-48EE-BD90-4AB74FEE16FE](https://user-images.githubusercontent.com/17108995/178146948-8603ff20-b262-480e-9b1f-f214a5d0eca1.png)

new version out. Uat and regular 😎
