### ISSUE TITLE
Snapshot options restoration 

### ISSUE THREAD

**Issue by Vweber73** [vAmigaWeb/vAmigaWeb#96]
Upon restoring a snapshot, the options it was created with (memory types and amount, clock speed, rendering,...,) are properly restored, but are not reflected in the option list. It is confusing since you don't know the options you are running. The list should be restored upon restoration of snapshot; however, the default options should be kept when restarting the app, they should not be overriden with the snapshot values permanently.

**Comment by mithrendal** [comment]
did it for the ntsc switch which will be restored rom snapshot ...

pushed to uat https://vamigaweb.github.io/uat/

the other are still to do ...

**Comment by Vweber73** [comment]
Great, thanks !

**Comment by mithrendal** [comment]
just pushed to official version ...

restoring 

- overclock setting
- agnus revision


more follows soon...

**Comment by Vweber73** [comment]
It seems fine, many thanks!
Just one thing, if you reset the amiga, the settings are still flagged as "snapshot", shouldn't they be back to unflagged? Not sure...
Cheers

**Comment by mithrendal** [comment]
>Just one thing, if you reset the amiga, the settings are still flagged as "snapshot", shouldn't they be back to unflagged? Not sure...

me not so sure either ... lets try the mac version...

I just checked the mac version and @dirkwhoffmann does the same as vAmigWeb i.e. upon snapshot restoration the settings are updated (but without flagging this where vAmigaWeb flags this) and upon reset the snapshot settings still survive ...

lets think ...

the question is what reset means... when its meant as a machine reset (CTRL+left Amiga key + right Amiga key) then it does perfectly the right thing in keeping the snapshots settings... 

If  one understands reset as a emulator reset or reset of the emulator settings then it is wrong and the settings should be reverted/resetted to the saved user settings ...

Maybe in the settings dialog we could add a button `revert to...` with the following values...

`revert to ...`
- `A1000 OCS`
- `A500 ECS`
- `big flagship (2MB chip + 8MB fast+ 14Mhz)`
- `saved configuration`

I think @mras0 proposed something like this in #100 ...

>Might be an idea to have some kind of one-click way to select a few useful defaults (A500 expanded, A500 plain, A600, Monster (28MHz + 8MB fast)) - Don't go overboard, just a few well chosen options. Ideally this should also choose the correct KS ROM if installed (maybe warn if it isn't).

**Comment by mras0** [comment]
My comment to the linked issue relates to how you configure the emulator in general. It was a suggestion on how to (I think) more easily configure many things at once.

IMO a soft reset (C+A+A or reset instruction) should never change hardware settings. The machine is still (logically) powered on when that happens. WinUAE behaves the same way, i.e. when you restore a snapshot the machine configuration is changed, and if you C+A+A afterwards it reboots with the snapshot's HW config (i.e. unchanged).

My mental model of snapshots is that you warp to a specific setting in more than one way. E.g. playing shadow of beast on an A500 or using WB on a A600. C+A+A should reboot the game / WB in the same environment.

After power-off, I think it's fine, and maybe best, to restore the user's defaults. The user has finished their trip to that special place (the saved state) and can always go back via the snapshot.

**Comment by Vweber73** [comment]
Hi,
I just noticed a small bug, with restoration of snapshot, all memory types are labelled as chip:

![Screenshot_20220626-183356_Chrome](https://user-images.githubusercontent.com/92450215/175824496-b73d412c-a944-416a-b27f-824bf45e683a.jpg)

Anything new? 
Cheers

**Comment by mithrendal** [comment]
I fixed this already 2 days ago in the regular version ... in uat version the bug is still present ... was a silly copy & paste error...

currently I am working/thinking for the installation/update procedure ... I want it to be as transparent as possible ... i.e. update notifications and also the user should have the possibility to opt out of an update because it would otherwise destroy his snapshots ... even to the point that he may want to choose to disable update notifications at all...

**Comment by Vweber73** [comment]
Excellent, thanks! So I will revert back to the normal version. I have not found a way to keep them both at the same time on the phone...

**Comment by Vweber73** [comment]
Actually, yes, this time I could installed the normal version while keeping the uat one.. Must have done something wrong previously.

**Comment by Vweber73** [comment]
Hi,
I guess the blotter accuracy settings is not restored, right? I use it for Interceptor as discussed (0 is needed when overclocking...)
Cheers

**Comment by mithrendal** [comment]
hi,
thats right ... we want that too ? then I will add it .. I wonder if we do need it for collision settngs too ... maybe ... yes ...

**Comment by Vweber73** [comment]
I can't think of any software that I know that would spend on collision settings (blitter is more obvious) but it could exist...
Cheers

**Comment by mithrendal** [comment]
Hi 
restored blitter compatibility settings from a snapshot...

also upgraded to latest 2.1b4 vAmigaCore which introduces ECS Denise with super hires capabilites ... of course this setting is also then restored from snapshot

uploaded it to uat version

**Comment by Vweber73** [comment]
Hi,
Many thanks!
I don't see the "(snapshot)" mention for blitter accuracy in the UI?
Also, I don't see any setting to select OCS/ECS Denise, I guess it is ECS by default as it doesn't harm anything?
Cheers

**Comment by mithrendal** [comment]
>Btw could kickstart version be part of the snapshot settings as well?

vAmigaWeb gives already the information about what kickstart currently is installed into the amiga vm 

I just tried ... I was on kick1.3 and then I loaded a kick2.0 snapshot ... switch to rom settings and it shows this

![image](https://user-images.githubusercontent.com/17108995/180663315-0252b614-b9da-4bd9-8cb6-72258d3c5586.png)

see the information (top part) is updated to kick 2.0

only the filename in the selection box (at the bottom) is not updated ... maybe we can just write the words  `from snapshot` into it ? What do you think?

**Comment by Vweber73** [comment]
Yes that would be perfect!
ECS Denise also makes the bottom lines of workbench 3.0 garbage... I guess this is going to be fixed. Dou you know if Productivity mode is planned to be supported?
Cheers

**Comment by mithrendal** [comment]
Will do after holiday. This week I have no computer in my hands. Enjoying beach and the sea. 

@dirkwhoffmann do you know about this productivity mode ? I never heard of it.

**Comment by Vweber73** [comment]
Well deserved vacation, enjoy! :)
Productivity is the other mode mainly brought by ECS Denise, aside from Superhires.
Cheers

**Comment by dirkwhoffmann** [comment]
Productivity modes won't be supported, because all non-standard modes (all modes requiring a multi-sync monitor) don't play well with vAmiga's internal architecture.

**Comment by Vweber73** [comment]
Noted with thanks.

**Comment by mithrendal** [comment]
when restoring from snapshot the kickstart dialog shows the restored kickstart now ....


![image](https://user-images.githubusercontent.com/17108995/210271533-52f2b912-ee9f-4043-a141-0ee3310cd7d5.png)


d466b64b2df655e82ef239b4904e2c1a0f23a7f9
