### ISSUE TITLE
prevent auto-off, screen off or dimming during emulation 

### ISSUE THREAD

**Issue by Vweber73** [vAmigaWeb/vAmigaWeb#97]
The app follows Android settings (which don't have a "never" anymore) to auto-off. 
You can bypass this with a third-party app (like Wakey) but this is cumbersome.
Some apps manage to stay always on by themselves, e.g. Netflix, thanks God, does not off the phone every 30 seconds while watching a video :)
So there is certainly a way to prevent this... All the more that the Cpcemu Amstrad CPC  emulator managed to do it after I made the same remark to him :)
Cheers

**Comment by mithrendal** [comment]
>Some apps manage to stay always on by themselves, e.g. Netflix, thanks God, does not off the phone every 30 seconds while watching a video :)

are these PWAs?

maybe we have to study this article
https://developer.chrome.com/blog/page-lifecycle-api/

**Comment by Vweber73** [comment]
Oops you're right, Netflix is a full apo, not a PWA, and I have no idea on the restrictions on PWA... But I could see that Wakey manages to keep vAmigaWeb alive. Keep Alive ! does not, but it was last updated in 2017, some changes must have changed deeply in Android since then...

**Comment by mithrendal** [comment]
I found a way to prevent auto off

https://developer.mozilla.org/en-US/docs/Web/API/Screen_Wake_Lock_API

**Comment by mithrendal** [comment]
<img width="668" alt="image" src="https://github.com/vAmigaWeb/vAmigaWeb/assets/17108995/c774c4db-90f9-457a-8c34-82d1742a7065">

added the `wake lock` setting, it is a persistant setting. When emulation is running it prevents the device from dimming or shutting the screen off. On the other hand - when emulation is paused then OS is allowed to dim or shut off the screen for energy saving. When wake lock setting is off then it is up to the underlying system. 

Tested in chrome for mac where it is fully working ... On safari 16 it is only partially supported ... see safari 17 [changelog](https://developer.apple.com/documentation/safari-release-notes/safari-17-release-notes) which is currently in beta will fix this.  It will come out somewhen in september/october when apple brings the new phones

```
Safari 17 Beta Release Notes
----------------------------
...
* Fixed Wake Lock permission denied after visibilitychange. (108279602)
* Fixed Wake Lock API for web apps saved to the home screen. (107284303)
...
```


@Vweber73 published to http://vamigaweb.github.io can we close ?

**Comment by mithrendal** [comment]
vAmigaWeb fully supports wake lock now
