### ISSUE TITLE
Small glitches with overclocking 

### ISSUE THREAD

**Issue by Vweber73** [vAmigaWeb/vAmigaWeb#98]
If you overclock to 35Mhz and play Interceptor demo, towards the end (just before landing), you'll see the HDG text (in the information windows) corrupted with an horizontal bar across the text.

This does not happen at normal speed, and it does not happen in Retroarch/PUAE at any speed, with comparable settings (ECS Amiga with 68000, only overlocked to 35Mhz).

**Comment by mithrendal** [comment]
![image](https://user-images.githubusercontent.com/17108995/170839713-f40512fd-e73a-4e26-ad87-54c7df8f87a7.png)

**Comment by Vweber73** [comment]
Yes... And sometimes bigger.
I wonder if the processor is too fast for the blitter or something... Maybe one of the blitter settings would solve it ?

**Comment by mithrendal** [comment]
does not happen with chip and sow ram ...

just checked the mac Version of vAmiga

![image](https://user-images.githubusercontent.com/17108995/170840432-b1de65bc-7d3a-493c-842e-48f4e9ad2cda.png)

same problem there ...

@dirkwhoffmann @mras0 should we open an issue in vAmiga main project ?

**Comment by mithrendal** [comment]
@mras0 does the glitch happen on your A1200 too ?

**Comment by Vweber73** [comment]
What I can say is that it does not seem to happen in PUAE in A1200 standard configuration.

**Comment by mras0** [comment]
The disk version has some graphical issues even with a stock A1200 config, and crashes if my accelerator is enabled. Using the WHDLoad version I can start the game, but there are quite a number of graphical issues looking a bit like the screenshot, but also the plane flashing, etc. I also got the plane stuck after a couple of minutes of game time (burning fuel but not moving).

I don't know if those exact glitches matches the emulated HW configuration, but the bottom line is that the game does have issues on faster Amigas.

**Comment by Vweber73** [comment]
Strange ! The "cracked by ah-ah" version I use works flawlessly on PUE with any configuration and overclocking. And on vAmigaWeb the only issue is very small glitches, nothing drastic like you describe. Maybe the disk version ?

**Comment by mras0** [comment]
Maybe the crack contains extra fixes, but probably not. If I turn off "Wait for blitter" (which is enabled by default in quickstart A1200 configuration) I get some glitches as well, though not as many on the real HW. AFAIK *UAE doesn't have 100% accurate 68020 emulation as some internal timings are still unknown.

**Comment by mithrendal** [comment]
maybe @dirkwhoffmann can run it with his overclocked ACA500 board in his A500, when it does have issues there too then it is probably as @mras0 assumes a game bug and we can close it...

**Comment by Vweber73** [comment]
But then, why does PUAE run it with no glitches ? :)

**Comment by mras0** [comment]
> But then, why does PUAE run it with no glitches ? :)

Inaccurate emulation (likely intentional due to the "Wait for blitter" flag I mentioned above).

A brief history of Amiga emulation (abridged):
1995-2005: Making glitches go away
2005-present: Making glitches glitches come back in the right way

**Comment by Vweber73** [comment]
Ah... Amazing ! :)

**Comment by mithrendal** [comment]
@Vweber73  tested ... you can drive the vAmiga core inaccurate too 😎 just set it to blitter level 0 ... that makes the glitches go away... 

now I wonder how do you will play interceptor ... 🤔

- accurate emulation but with glitches in overclocking  
or
- inaccurate but without glitches which would be visible on real hardware 😬

tough decision no ? 😂  okay tell us which one will you choose ?

**Comment by mras0** [comment]
This isn't a Saw movie, so we don't have to choose between too bad options 😄. Looks like JOTD might be working on improving the WHDload version ([EAB thread](http://eab.abime.net/showthread.php?t=110751)).

**Comment by Vweber73** [comment]
Very interesting guys, many thanks ! Indeed Blitter accuracy set to 0 solves the problem, so it is a cornelian choice ! :)
And this EAB thread is very interesting too !
Seems that Interceptor is a legendary early game that was very well done but not planned with faster Amigas in mind (normal for 1988), and that now it is a very good benchmarking platform !
For the record, I'm like one guy that is mentionned in the thread - I did buy (well, beg my parents to buy) an A500 after seeing Interceptor at a friend's. I remember coming back home very depressed looking at my Amstrad CPC6128, utterly unable to do anything remotely similar, as much as I loved it. The divorce with Amstrad in favor of Commodore started here :)

**Comment by mithrendal** [comment]
in that eab thread on page2 paraj also mentioned our issue here ... he said

... on 060/50 

- 3rd person view the heading/speed/height indicators have graphical glitches (like they're being drawn to the active display or maybe missing blitter waits elsewhere) 

@Vweber73 do you like to close the issue ?  

🤤 really hoping they can fix the too quick physics in interceptor...

**Comment by Vweber73** [comment]
Ok, done deal ! :) Many thanks

**Comment by mras0** [comment]
It's not really more confirmation. As you may have guessed I'm the one who made that comment :)
